In [1]:
# Importing necessary libraries for web scrapping flight price data.

import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import warnings
warnings.filterwarnings('ignore')

In [40]:
# Connecting to the webdriver.

driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [41]:
# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=376142335919'
driver.get(url)

In [42]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)

157

In [43]:
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

['SpiceJet',
 'Air Asia',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'IndiGo',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Air India',
 'IndiGo',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Air India',
 'Air Asia',
 'IndiGo',
 'Air India',
 'Vistara',
 'Air Asia',
 'Vistara',
 'Air India',
 'Air Asia',
 'Air Asia',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Go First',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Go First',
 'IndiGo',
 'Air India',
 'Air India',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo']

In [44]:
flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

157

In [45]:
Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

['SG-2976/279',
 'I5-743/762',
 'G8-2501',
 'G8-530',
 'G8-334',
 'G8-336',
 'G8-323',
 'G8-346',
 'G8-354',
 'G8-330',
 '6E-2117/265',
 'SG-8709',
 'SG-8169',
 'SG-8244',
 'SG-8701',
 '6E-5345/5235',
 '6E-5218',
 '6E-2519',
 '6E-2112',
 '6E-2526',
 '6E-2328',
 'AI-678',
 'AI-805',
 'AI-887',
 'AI-605',
 'AI-814',
 'AI-665',
 'AI-865',
 '6E-2176',
 '6E-2505',
 'UK-975',
 'AI-441',
 '6E-2208/5282',
 'G8-717/537',
 'G8-719/459',
 'G8-717/413',
 'G8-143/352',
 'G8-713/392',
 'G8-237/388',
 'G8-719/2505',
 'AI-815/610',
 'AI-815/642',
 'AI-506/610',
 'AI-506/642',
 '6E-2075',
 '6E-2017',
 '6E-2016',
 '6E-5318',
 '6E-864',
 '6E-2084',
 '6E-2114',
 '6E-2138',
 '6E-6814',
 'I5-784/334',
 'UK-981',
 'UK-927',
 'UK-933',
 'UK-943',
 'UK-993',
 'UK-951',
 'UK-955',
 'UK-995',
 'UK-945',
 'AI-863',
 'UK-963',
 'AI-624',
 'AI-636',
 'UK-811/854',
 'UK-811/864',
 'UK-811/866',
 'AI-807/642',
 'AI-803/610',
 'AI-803/642',
 'AI-504/604',
 'AI-512/604',
 'AI-815/604',
 'AI-506/604',
 'AI-443/400',
 'AI-807/604',
 '6E-2049/6699',
 '6E-2411/392',
 '6E-2049/6175',
 '6E-2411/6699',
 '6E-2411/6175',
 '6E-5603/5383',
 'UK-635/614',
 'UK-807/858',
 'UK-819/854',
 'UK-819/864',
 'UK-817/866',
 'UK-819/866',
 'UK-855/556',
 'I5-773/472',
 'I5-773/337',
 'I5-773/335',
 'AI-839/616',
 'I5-740/613',
 '6E-2033/6182',
 'AI-471/644',
 'UK-833/828',
 'I5-857/334',
 'UK-957',
 'AI-475/646',
 'I5-1228/613',
 'I5-1228/1782',
 'UK-913/888',
 '6E-123/6548',
 '6E-319/6548',
 '6E-2033/2046',
 'AI-415/732',
 'AI-883/684',
 'AI-883/697',
 '6E-2216/5259',
 'UK-855/844',
 'UK-855/842',
 'AI-558/569',
 'AI-554/569',
 'UK-835/828',
 'UK-839/828',
 'UK-833/826',
 'UK-835/822',
 'UK-837/828',
 'AI-558/672',
 'UK-637/652',
 'UK-847/844',
 'UK-833/824',
 '6E-6231/5232',
 'G8-286/2606',
 'UK-985',
 '6E-607/6182',
 '6E-153/6182',
 'UK-929/918',
 'G8-286/372',
 '6E-6492/2444',
 'AI-554/574',
 'AI-540/569',
 'UK-929/956',
 '6E-6492/803',
 '6E-607/2046',
 'UK-839/824',
 'UK-929/936',
 'AI-439/672',
 'AI-558/571',
 'AI-429/672',
 'AI-429/574',
 'UK-969/918',
 '6E-6187/274',
 '6E-2204/5237',
 '6E-7403/5235',
 'UK-969/956',
 '6E-6475/6208',
 '6E-6475/6935',
 '6E-184/6208',
 'I5-745/338',
 '6E-184/803',
 '6E-902/6598',
 '6E-6201/6794']

In [46]:
source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

314

In [47]:
sources=[]
for i in source:
    sources.append(i.text)
sources

['New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai',
 'New Delhi',
 'Mumbai']

In [48]:
list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]

In [49]:
len(list1)

157

In [50]:
list1

['Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai']

In [51]:
list2=sources[::2]

In [52]:
len(list2)

157

In [53]:
list2

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [54]:
duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

157

In [55]:
duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

['14h 20m',
 '8h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '5h 40m',
 '1h 55m',
 '2h 05m',
 '2h 15m',
 '2h 15m',
 '9h 05m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '2h 25m',
 '2h 35m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '2h 15m',
 '2h 20m',
 '2h 15m',
 '2h 25m',
 '8h 40m',
 '3h 55m',
 '4h 15m',
 '5h 00m',
 '5h 45m',
 '8h 35m',
 '9h 45m',
 '10h 15m',
 '5h 55m',
 '7h 45m',
 '11h 45m',
 '13h 35m',
 '1h 55m',
 '2h 10m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '8h 10m',
 '2h 00m',
 '2h 05m',
 '2h 05m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '2h 25m',
 '3h 45m',
 '14h 40m',
 '15h 05m',
 '17h 45m',
 '6h 20m',
 '15h 20m',
 '17h 10m',
 '14h 20m',
 '16h 05m',
 '19h 55m',
 '25h 45m',
 '5h 05m',
 '18h 30m',
 '4h 30m',
 '4h 35m',
 '5h 40m',
 '8h 00m',
 '9h 10m',
 '4h 50m',
 '4h 50m',
 '11h 40m',
 '6h 05m',
 '6h 30m',
 '7h 15m',
 '9h 10m',
 '7h 20m',
 '6h 20m',
 '8h 00m',
 '10h 55m',
 '12h 05m',
 '10h 50m',
 '6h 10m',
 '4h 50m',
 '25h 20m',
 '5h 35m',
 '2h 15m',
 '24h 50m',
 '9h 30m',
 '11h 30m',
 '11h 00m',
 '4h 30m',
 '6h 15m',
 '8h 15m',
 '24h 30m',
 '10h 10m',
 '26h 20m',
 '8h 25m',
 '5h 35m',
 '20h 05m',
 '12h 30m',
 '20h 20m',
 '12h 50m',
 '19h 20m',
 '6h 50m',
 '15h 35m',
 '15h 25m',
 '21h 40m',
 '5h 15m',
 '13h 05m',
 '14h 50m',
 '4h 30m',
 '7h 30m',
 '2h 15m',
 '7h 50m',
 '9h 30m',
 '8h 55m',
 '8h 35m',
 '6h 40m',
 '10h 55m',
 '11h 30m',
 '21h 25m',
 '5h 20m',
 '9h 55m',
 '8h 50m',
 '12h 20m',
 '12h 10m',
 '14h 20m',
 '8h 10m',
 '13h 00m',
 '12h 15m',
 '4h 45m',
 '6h 55m',
 '6h 30m',
 '24h 45m',
 '9h 50m',
 '4h 35m',
 '6h 30m',
 '6h 40m',
 '9h 00m',
 '6h 15m',
 '4h 55m']

In [56]:
arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

157

In [57]:
Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

['20:10',
 '04:55',
 '02:40',
 '06:00',
 '07:20',
 '14:35',
 '18:00',
 '20:00',
 '22:30',
 '21:00',
 '11:05',
 '18:10',
 '20:00',
 '02:00',
 '06:45',
 '05:10',
 '06:30',
 '23:00',
 '04:45',
 '08:45',
 '10:00',
 '10:10',
 '20:00',
 '07:00',
 '21:20',
 '22:30',
 '08:00',
 '10:00',
 '14:15',
 '11:00',
 '05:45',
 '17:50',
 '22:45',
 '17:30',
 '06:00',
 '17:30',
 '10:40',
 '22:15',
 '12:45',
 '06:00',
 '15:35',
 '15:35',
 '09:45',
 '09:45',
 '08:10',
 '19:20',
 '15:45',
 '16:25',
 '17:25',
 '20:20',
 '21:45',
 '12:00',
 '07:15',
 '16:30',
 '21:40',
 '09:30',
 '15:30',
 '07:30',
 '12:50',
 '14:20',
 '17:45',
 '10:20',
 '11:40',
 '14:00',
 '08:50',
 '19:00',
 '14:30',
 '05:35',
 '05:35',
 '05:35',
 '17:00',
 '06:10',
 '06:10',
 '21:10',
 '19:25',
 '15:35',
 '09:45',
 '04:45',
 '17:00',
 '10:25',
 '06:55',
 '10:25',
 '06:55',
 '06:55',
 '15:20',
 '11:00',
 '20:40',
 '14:10',
 '14:10',
 '16:05',
 '14:10',
 '18:40',
 '20:00',
 '20:00',
 '20:00',
 '21:50',
 '08:10',
 '23:40',
 '13:15',
 '07:40',
 '19:05',
 '20:40',
 '12:55',
 '09:30',
 '09:30',
 '05:55',
 '16:55',
 '15:10',
 '23:40',
 '16:45',
 '22:00',
 '22:00',
 '09:25',
 '18:40',
 '18:40',
 '19:40',
 '11:50',
 '20:10',
 '13:40',
 '07:40',
 '20:10',
 '17:35',
 '19:40',
 '16:45',
 '11:10',
 '07:40',
 '05:15',
 '10:55',
 '19:45',
 '22:00',
 '20:20',
 '21:20',
 '10:55',
 '13:20',
 '11:50',
 '20:40',
 '21:20',
 '13:20',
 '22:00',
 '13:40',
 '21:20',
 '05:45',
 '19:40',
 '09:45',
 '09:45',
 '18:00',
 '15:25',
 '13:00',
 '07:45',
 '18:00',
 '06:20',
 '06:20',
 '09:40',
 '13:15',
 '09:40',
 '16:45',
 '18:40']

In [58]:
dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

157

In [59]:
Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t

['10:30\n+ 1 day',
 '13:05',
 '04:50',
 '08:10',
 '09:30',
 '16:45',
 '20:10',
 '22:10',
 '00:40\n+ 1 day',
 '23:15',
 '16:45',
 '20:05',
 '22:05',
 '04:15',
 '09:00',
 '14:15',
 '08:45',
 '01:20\n+ 1 day',
 '07:10',
 '11:10',
 '12:35',
 '12:20',
 '22:10',
 '09:15',
 '23:35',
 '00:45\n+ 1 day',
 '10:20',
 '12:25',
 '16:30',
 '13:20',
 '08:00',
 '20:15',
 '07:25\n+ 1 day',
 '21:25',
 '10:15',
 '22:30',
 '16:25',
 '06:50\n+ 1 day',
 '22:30',
 '16:15',
 '21:30',
 '23:20',
 '21:30',
 '23:20',
 '10:05',
 '21:30',
 '18:00',
 '18:40',
 '19:40',
 '22:35',
 '00:00\n+ 1 day',
 '14:20',
 '09:40',
 '00:40\n+ 1 day',
 '23:40',
 '11:35',
 '17:35',
 '09:40',
 '15:00',
 '16:30',
 '19:55',
 '12:35',
 '13:55',
 '16:20',
 '11:15',
 '21:25',
 '18:15',
 '20:15',
 '20:40',
 '23:20',
 '23:20',
 '21:30',
 '23:20',
 '11:30\n+ 1 day',
 '11:30\n+ 1 day',
 '11:30\n+ 1 day',
 '11:30\n+ 1 day',
 '09:50',
 '11:30\n+ 1 day',
 '14:55',
 '11:30',
 '16:05',
 '14:55',
 '16:05',
 '20:10',
 '15:50',
 '08:20\n+ 1 day',
 '20:15',
 '20:40',
 '23:20',
 '23:20',
 '02:00\n+ 1 day',
 '02:20\n+ 1 day',
 '04:00\n+ 1 day',
 '06:55\n+ 1 day',
 '09:55\n+ 1 day',
 '19:00',
 '05:50\n+ 1 day',
 '18:05',
 '09:00\n+ 1 day',
 '00:40\n+ 1 day',
 '22:55',
 '13:45\n+ 1 day',
 '19:00',
 '21:00',
 '16:55',
 '21:25',
 '21:25',
 '07:55\n+ 1 day',
 '17:15\n+ 1 day',
 '08:10\n+ 1 day',
 '00:20\n+ 2 days',
 '17:50',
 '00:15\n+ 1 day',
 '14:45\n+ 1 day',
 '08:10\n+ 1 day',
 '08:10\n+ 1 day',
 '09:00\n+ 1 day',
 '09:00\n+ 1 day',
 '14:30',
 '11:45\n+ 1 day',
 '09:00\n+ 1 day',
 '17:20\n+ 1 day',
 '22:00',
 '00:15\n+ 1 day',
 '22:30',
 '09:45',
 '18:25',
 '22:00',
 '05:50\n+ 1 day',
 '05:50\n+ 1 day',
 '06:15\n+ 1 day',
 '19:30',
 '20:00',
 '22:45',
 '08:10\n+ 1 day',
 '18:45\n+ 1 day',
 '18:40',
 '07:55\n+ 1 day',
 '22:30',
 '09:40\n+ 1 day',
 '17:55',
 '10:00\n+ 1 day',
 '17:55',
 '22:45',
 '06:15\n+ 1 day',
 '20:10',
 '19:55',
 '14:15',
 '18:45\n+ 1 day',
 '16:10',
 '10:55',
 '16:10',
 '19:55',
 '18:40',
 '23:00',
 '23:35']

In [60]:
total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

157

In [61]:
Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t

['14h 20m',
 '8h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '5h 40m',
 '1h 55m',
 '2h 05m',
 '2h 15m',
 '2h 15m',
 '9h 05m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '2h 25m',
 '2h 35m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '2h 15m',
 '2h 20m',
 '2h 15m',
 '2h 25m',
 '8h 40m',
 '3h 55m',
 '4h 15m',
 '5h 00m',
 '5h 45m',
 '8h 35m',
 '9h 45m',
 '10h 15m',
 '5h 55m',
 '7h 45m',
 '11h 45m',
 '13h 35m',
 '1h 55m',
 '2h 10m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '8h 10m',
 '2h 00m',
 '2h 05m',
 '2h 05m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '2h 25m',
 '3h 45m',
 '14h 40m',
 '15h 05m',
 '17h 45m',
 '6h 20m',
 '15h 20m',
 '17h 10m',
 '14h 20m',
 '16h 05m',
 '19h 55m',
 '25h 45m',
 '5h 05m',
 '18h 30m',
 '4h 30m',
 '4h 35m',
 '5h 40m',
 '8h 00m',
 '9h 10m',
 '4h 50m',
 '4h 50m',
 '11h 40m',
 '6h 05m',
 '6h 30m',
 '7h 15m',
 '9h 10m',
 '7h 20m',
 '6h 20m',
 '8h 00m',
 '10h 55m',
 '12h 05m',
 '10h 50m',
 '6h 10m',
 '4h 50m',
 '25h 20m',
 '5h 35m',
 '2h 15m',
 '24h 50m',
 '9h 30m',
 '11h 30m',
 '11h 00m',
 '4h 30m',
 '6h 15m',
 '8h 15m',
 '24h 30m',
 '10h 10m',
 '26h 20m',
 '8h 25m',
 '5h 35m',
 '20h 05m',
 '12h 30m',
 '20h 20m',
 '12h 50m',
 '19h 20m',
 '6h 50m',
 '15h 35m',
 '15h 25m',
 '21h 40m',
 '5h 15m',
 '13h 05m',
 '14h 50m',
 '4h 30m',
 '7h 30m',
 '2h 15m',
 '7h 50m',
 '9h 30m',
 '8h 55m',
 '8h 35m',
 '6h 40m',
 '10h 55m',
 '11h 30m',
 '21h 25m',
 '5h 20m',
 '9h 55m',
 '8h 50m',
 '12h 20m',
 '12h 10m',
 '14h 20m',
 '8h 10m',
 '13h 00m',
 '12h 15m',
 '4h 45m',
 '6h 55m',
 '6h 30m',
 '24h 45m',
 '9h 50m',
 '4h 35m',
 '6h 30m',
 '6h 40m',
 '9h 00m',
 '6h 15m',
 '4h 55m']

In [62]:
total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

157

In [63]:
Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s

['1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop']

In [64]:
cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

157

In [65]:
price=[]
for i in cost:
    price.append(i.text)
price

['4,775',
 '5,383',
 '5,452',
 '5,452',
 '5,452',
 '5,452',
 '5,452',
 '5,452',
 '5,452',
 '5,452',
 '5,592',
 '5,802',
 '5,802',
 '5,802',
 '5,802',
 '5,898',
 '5,899',
 '5,899',
 '5,899',
 '5,899',
 '5,899',
 '5,955',
 '5,955',
 '5,955',
 '5,955',
 '5,955',
 '5,955',
 '5,955',
 '6,059',
 '6,059',
 '6,375',
 '6,480',
 '6,600',
 '6,873',
 '6,873',
 '6,873',
 '6,873',
 '6,873',
 '6,873',
 '6,873',
 '7,194',
 '7,194',
 '7,194',
 '7,194',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,388',
 '7,388',
 '7,388',
 '7,457',
 '7,457',
 '7,457',
 '7,940',
 '7,940',
 '7,940',
 '7,940',
 '8,127',
 '8,202',
 '8,668',
 '8,668',
 '8,668',
 '8,668',
 '8,668',
 '8,969',
 '9,000',
 '9,263',
 '9,331',
 '9,331',
 '9,331',
 '9,331',
 '9,347',
 '9,371',
 '9,371',
 '9,371',
 '9,489',
 '9,630',
 '9,733',
 '9,840',
 '9,909',
 '10,050',
 '10,155',
 '10,647',
 '10,732',
 '10,732',
 '10,890',
 '11,257',
 '11,257',
 '11,259',
 '11,446',
 '11,835',
 '11,835',
 '11,939',
 '12,255',
 '12,255',
 '12,276',
 '12,276',
 '12,293',
 '12,293',
 '12,518',
 '13,076',
 '13,133',
 '13,221',
 '13,409',
 '13,410',
 '13,463',
 '13,568',
 '13,646',
 '13,830',
 '14,039',
 '14,039',
 '14,074',
 '14,172',
 '14,879',
 '14,880',
 '14,901',
 '14,914',
 '15,428',
 '15,824',
 '15,846',
 '16,067',
 '16,245',
 '16,371',
 '16,770',
 '16,770',
 '17,224',
 '17,452',
 '17,730',
 '17,940',
 '18,064',
 '19,465',
 '20,866',
 '21,799',
 '22,706',
 '24,429',
 '26,062',
 '28,500']

In [66]:
meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

80

In [67]:
Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info

['Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal']

In [68]:
# Creating the Dataframe.

flights = pd.DataFrame({})
flights['Airline'] = Airline
flights['Destination'] = list1
flights['Source'] = list2
flights['Arrival_time'] = Arr_t
flights['Departure_time'] =Dep_t
flights['Total_Stops']=Total_s
flights['Total_Duration']=duration
flights['Additional_Info']=pd.Series(Add_info)
flights['Price']=price
flights

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,SpiceJet,Mumbai,New Delhi,20:10,10:30\n+ 1 day,1 Stop,14h 20m,Free Meal,"4,775"
1,Air Asia,Mumbai,New Delhi,04:55,13:05,1 Stop,8h 10m,Free Meal,"5,383"
2,Go First,Mumbai,New Delhi,02:40,04:50,Non Stop,2h 10m,Free Meal,"5,452"
3,Go First,Mumbai,New Delhi,06:00,08:10,Non Stop,2h 10m,Free Meal,"5,452"
4,Go First,Mumbai,New Delhi,07:20,09:30,Non Stop,2h 10m,Free Meal,"5,452"
...,...,...,...,...,...,...,...,...,...
152,IndiGo,Mumbai,New Delhi,09:40,16:10,1 Stop,6h 30m,NaN,"21,799"
153,Air Asia,Mumbai,New Delhi,13:15,19:55,1 Stop,6h 40m,NaN,"22,706"
154,IndiGo,Mumbai,New Delhi,09:40,18:40,1 Stop,9h 00m,NaN,"24,429"
155,IndiGo,Mumbai,New Delhi,16:45,23:00,1 Stop,6h 15m,NaN,"26,062"
156,IndiGo,Mumbai,New Delhi,18:40,23:35,1 Stop,4h 55m,NaN,"28,500"

In [69]:
# Connecting to the webdriver.

driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [70]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=DEL&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1119088783999'
driver.get(url)

In [72]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)

154

In [73]:
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

['SpiceJet',
 'SpiceJet',
 'Vistara',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Air Asia',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'Air Asia',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Air India',
 'Go First',
 'Air Asia',
 'Vistara',
 'Go First',
 'Go First',
 'IndiGo',
 'IndiGo',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Air India',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'Go First',
 'Go First',
 'Go First',
 'IndiGo',
 'Go First',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Go First',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air Asia',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Air India',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Go First',
 'IndiGo',
 'Air India',
 'IndiGo',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Air Asia',
 'IndiGo',
 'Vistara',
 'IndiGo',
 'Air India',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Go First',
 'Vistara',
 'Vistara']

In [74]:
flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

154

In [75]:
Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

['SG-535',
 'SG-537',
 'UK-814',
 'I5-749',
 '6E-2402',
 '6E-6813',
 'AI-509',
 'AI-808',
 '6E-2053',
 '6E-2401',
 'SG-531/8184',
 'SG-531/8937',
 'SG-8134',
 'I5-386/767',
 'I5-942/766',
 'I5-1532/789',
 'I5-976/738',
 'I5-1426/732',
 '6E-6247',
 '6E-5021',
 '6E-2433',
 '6E-6621',
 '6E-2174',
 '6E-2186',
 '6E-5039',
 '6E-735',
 '6E-6753/6602',
 '6E-687/2337',
 '6E-415/2205',
 '6E-469/2405',
 '6E-528/5203',
 'I5-1731',
 'I5-996',
 'UK-818',
 'AI-503',
 'AI-804',
 'AI-507',
 '6E-869',
 'I5-1528',
 'SG-136',
 'UK-808',
 'UK-810',
 'UK-816',
 'UK-802',
 'AI-1808',
 'UK-812',
 'AI-511',
 'G8-241/172',
 'I5-819/549',
 'UK-551/974',
 'G8-241/2541',
 'G8-241/176',
 '6E-6365/2008',
 '6E-6743/6102',
 'G8-320/2508',
 'G8-399/329',
 'G8-320/329',
 'G8-399/327',
 'AI-564/539',
 'UK-864/986',
 'UK-854/986',
 'SG-768/8729',
 'SG-768/481',
 '6E-638/2324',
 'G8-401/146',
 'G8-274/132',
 'G8-801/718',
 '6E-528/2369',
 'G8-721/174',
 '6E-6876/2472',
 '6E-6491/6372',
 'AI-642/864',
 'AI-642/806',
 'AI-610/864',
 'AI-642/866',
 'AI-642/809',
 'AI-610/806',
 'AI-610/866',
 'AI-610/809',
 'AI-642/677',
 'G8-803/714',
 '6E-6563/2419',
 'UK-866/625/636',
 'UK-866/613/628',
 'UK-866/625/628',
 'UK-864/625/636',
 'UK-854/625/636',
 'UK-864/613/628',
 'UK-864/625/628',
 'UK-854/613/628',
 'UK-854/625/628',
 'UK-864/950',
 'UK-854/950',
 'UK-858/994',
 'UK-866/954',
 'UK-866/928',
 'UK-864/954',
 'UK-854/954',
 'UK-864/928',
 'UK-854/928',
 'UK-866/994',
 'UK-551/998',
 'UK-508/986',
 '6E-6067/2213',
 'UK-551/992',
 'AI-640/809',
 'AI-640/677',
 'AI-640/442',
 'AI-640/687',
 'I5-741',
 'UK-553/974',
 '6E-855/2324',
 'UK-508/944',
 'UK-508/902',
 '6E-116/6617',
 '6E-6067/2287',
 'AI-516/840',
 '6E-6104/2587',
 'AI-642/633/436',
 'AI-610/633/436',
 'AI-642/633/434',
 '6E-6178/771',
 '6E-408/5004',
 '6E-6876/5004',
 '6E-537/2063',
 '6E-886/2063',
 'UK-551/972',
 'UK-897/880',
 'UK-897/890',
 '6E-6491/6606',
 '6E-537/6606',
 'UK-854/988',
 'G8-285/195',
 '6E-638/2287',
 'AI-893/884',
 '6E-886/2171',
 'UK-881/856',
 'UK-852/618',
 '6E-484/2171',
 'UK-657/638',
 'I5-1981/792',
 '6E-116/2419',
 'UK-657/707',
 '6E-6923/6204',
 'AI-564/538',
 'I5-1453/799',
 'I5-818/315',
 'I5-1574/315',
 'UK-755/722',
 '6E-469/7404',
 'UK-820',
 'G8-285',
 'UK-852/952',
 'UK-852/944']

In [76]:
source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

308

In [77]:
sources=[]
for i in source:
    sources.append(i.text)
sources

['Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi',
 'Bangalore',
 'New Delhi']

In [78]:
list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]

In [79]:
len(list1)

154

In [80]:
list1

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [81]:
list2=sources[::2]

In [82]:
len(list2)

154

In [83]:
list2

['Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore']

In [84]:
arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

154

In [85]:
Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

['18:30',
 '23:00',
 '21:10',
 '22:40',
 '20:40',
 '22:00',
 '19:20',
 '21:00',
 '23:20',
 '13:45',
 '10:25',
 '10:25',
 '17:20',
 '03:30',
 '15:00',
 '18:45',
 '20:55',
 '12:45',
 '04:25',
 '05:35',
 '07:00',
 '15:45',
 '18:00',
 '08:00',
 '16:50',
 '19:15',
 '13:25',
 '14:25',
 '08:45',
 '15:15',
 '17:15',
 '17:55',
 '19:50',
 '19:40',
 '17:00',
 '05:45',
 '11:45',
 '12:00',
 '05:45',
 '05:55',
 '08:00',
 '07:00',
 '11:30',
 '18:45',
 '08:00',
 '09:45',
 '15:00',
 '16:40',
 '09:05',
 '06:10',
 '16:40',
 '16:40',
 '07:30',
 '18:00',
 '18:50',
 '20:25',
 '18:50',
 '20:25',
 '14:00',
 '19:00',
 '18:30',
 '17:00',
 '17:00',
 '18:50',
 '15:40',
 '09:10',
 '06:20',
 '17:15',
 '06:30',
 '02:45',
 '12:40',
 '21:20',
 '21:20',
 '19:15',
 '21:20',
 '21:20',
 '19:15',
 '19:15',
 '19:15',
 '21:20',
 '18:30',
 '00:30',
 '21:35',
 '21:35',
 '21:35',
 '19:00',
 '18:30',
 '19:00',
 '19:00',
 '18:30',
 '18:30',
 '19:00',
 '18:30',
 '06:40',
 '21:35',
 '21:35',
 '19:00',
 '18:30',
 '19:00',
 '18:30',
 '21:35',
 '06:10',
 '11:05',
 '16:10',
 '06:10',
 '06:40',
 '06:40',
 '06:40',
 '06:40',
 '11:30',
 '20:30',
 '19:55',
 '11:05',
 '11:05',
 '22:30',
 '16:10',
 '07:25',
 '11:25',
 '21:20',
 '19:15',
 '21:20',
 '23:40',
 '05:15',
 '02:45',
 '10:30',
 '09:00',
 '06:10',
 '06:55',
 '06:55',
 '12:40',
 '10:30',
 '18:30',
 '15:50',
 '18:50',
 '16:20',
 '09:00',
 '12:50',
 '09:40',
 '07:25',
 '11:40',
 '04:50',
 '22:30',
 '11:40',
 '05:15',
 '14:00',
 '13:00',
 '05:30',
 '04:10',
 '10:40',
 '15:15',
 '17:50',
 '15:50',
 '09:40',
 '09:40']

In [86]:
dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

154

In [87]:
Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t

['21:15',
 '01:45\n+ 1 day',
 '23:45',
 '01:25\n+ 1 day',
 '23:35',
 '01:00\n+ 1 day',
 '22:20',
 '00:10\n+ 1 day',
 '02:10\n+ 1 day',
 '16:45',
 '19:50',
 '08:15\n+ 1 day',
 '19:30',
 '08:50',
 '20:45',
 '00:35\n+ 1 day',
 '03:55\n+ 1 day',
 '20:05',
 '07:15',
 '08:25',
 '09:50',
 '18:35',
 '20:50',
 '10:55',
 '19:45',
 '22:10',
 '19:00',
 '20:20',
 '15:25',
 '22:55',
 '02:05\n+ 1 day',
 '20:45',
 '22:50',
 '22:20',
 '19:45',
 '08:45',
 '14:45',
 '14:50',
 '08:35',
 '08:35',
 '10:35',
 '09:40',
 '14:10',
 '21:25',
 '10:50',
 '12:40',
 '18:00',
 '23:10',
 '14:30',
 '07:40\n+ 1 day',
 '21:50',
 '06:45\n+ 1 day',
 '13:00',
 '00:25\n+ 1 day',
 '02:00\n+ 1 day',
 '08:00\n+ 1 day',
 '08:00\n+ 1 day',
 '10:55\n+ 1 day',
 '19:50',
 '01:00\n+ 1 day',
 '01:00\n+ 1 day',
 '11:20\n+ 1 day',
 '18:50\n+ 1 day',
 '01:10\n+ 1 day',
 '21:45',
 '22:40',
 '21:15',
 '23:40',
 '14:30',
 '09:45',
 '20:40',
 '09:15\n+ 1 day',
 '10:15\n+ 1 day',
 '09:15\n+ 1 day',
 '11:20\n+ 1 day',
 '12:15\n+ 1 day',
 '10:15\n+ 1 day',
 '11:20\n+ 1 day',
 '12:15\n+ 1 day',
 '15:15\n+ 1 day',
 '00:50\n+ 1 day',
 '07:20',
 '14:40\n+ 1 day',
 '16:45\n+ 1 day',
 '16:45\n+ 1 day',
 '14:40\n+ 1 day',
 '14:40\n+ 1 day',
 '16:45\n+ 1 day',
 '16:45\n+ 1 day',
 '16:45\n+ 1 day',
 '16:45\n+ 1 day',
 '00:10\n+ 1 day',
 '00:10\n+ 1 day',
 '12:40',
 '07:55\n+ 1 day',
 '08:35\n+ 1 day',
 '07:55\n+ 1 day',
 '07:55\n+ 1 day',
 '08:35\n+ 1 day',
 '08:35\n+ 1 day',
 '12:40\n+ 1 day',
 '19:10',
 '01:00\n+ 1 day',
 '22:40',
 '22:30',
 '12:15',
 '15:15',
 '17:55',
 '18:40',
 '14:20',
 '07:40\n+ 1 day',
 '01:10\n+ 1 day',
 '16:55',
 '18:05',
 '04:20\n+ 1 day',
 '00:05\n+ 1 day',
 '23:10',
 '18:45',
 '09:30\n+ 1 day',
 '09:30\n+ 1 day',
 '15:00\n+ 1 day',
 '07:30\n+ 1 day',
 '11:10',
 '11:10',
 '16:30',
 '16:30',
 '10:55',
 '16:00',
 '19:55',
 '18:55',
 '18:55',
 '23:00',
 '03:00\n+ 1 day',
 '00:05\n+ 1 day',
 '03:50\n+ 1 day',
 '14:15',
 '00:40\n+ 1 day',
 '16:30',
 '14:15',
 '19:50',
 '11:45',
 '07:20\n+ 1 day',
 '16:25',
 '11:55',
 '23:25',
 '19:10',
 '10:45',
 '10:45',
 '20:50',
 '20:15',
 '20:30',
 '20:20',
 '14:50',
 '16:55']

In [88]:
total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

154

In [89]:
Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s

['Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop']

In [90]:
duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

154

In [91]:
duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

['2h 45m',
 '2h 45m',
 '2h 35m',
 '2h 45m',
 '2h 55m',
 '3h 00m',
 '3h 00m',
 '3h 10m',
 '2h 50m',
 '3h 00m',
 '9h 25m',
 '21h 50m',
 '2h 10m',
 '5h 20m',
 '5h 45m',
 '5h 50m',
 '7h 00m',
 '7h 20m',
 '2h 50m',
 '2h 50m',
 '2h 50m',
 '2h 50m',
 '2h 50m',
 '2h 55m',
 '2h 55m',
 '2h 55m',
 '5h 35m',
 '5h 55m',
 '6h 40m',
 '7h 40m',
 '8h 50m',
 '2h 50m',
 '3h 00m',
 '2h 40m',
 '2h 45m',
 '3h 00m',
 '3h 00m',
 '2h 50m',
 '2h 50m',
 '2h 40m',
 '2h 35m',
 '2h 40m',
 '2h 40m',
 '2h 40m',
 '2h 50m',
 '2h 55m',
 '3h 00m',
 '6h 30m',
 '5h 25m',
 '25h 30m',
 '5h 10m',
 '14h 05m',
 '5h 30m',
 '6h 25m',
 '7h 10m',
 '11h 35m',
 '13h 10m',
 '14h 30m',
 '5h 50m',
 '6h 00m',
 '6h 30m',
 '18h 20m',
 '25h 50m',
 '6h 20m',
 '6h 05m',
 '13h 30m',
 '14h 55m',
 '6h 25m',
 '8h 00m',
 '7h 00m',
 '8h 00m',
 '11h 55m',
 '12h 55m',
 '14h 00m',
 '14h 00m',
 '14h 55m',
 '15h 00m',
 '16h 05m',
 '17h 00m',
 '17h 55m',
 '6h 20m',
 '6h 50m',
 '17h 05m',
 '19h 10m',
 '19h 10m',
 '19h 40m',
 '20h 10m',
 '21h 45m',
 '21h 45m',
 '22h 15m',
 '22h 15m',
 '5h 10m',
 '5h 40m',
 '6h 00m',
 '10h 20m',
 '11h 00m',
 '12h 55m',
 '13h 25m',
 '13h 35m',
 '14h 05m',
 '15h 05m',
 '13h 00m',
 '13h 55m',
 '6h 30m',
 '16h 20m',
 '5h 35m',
 '8h 35m',
 '11h 15m',
 '12h 00m',
 '2h 50m',
 '11h 10m',
 '5h 15m',
 '5h 50m',
 '7h 00m',
 '5h 50m',
 '7h 55m',
 '15h 45m',
 '7h 20m',
 '12h 10m',
 '14h 15m',
 '17h 40m',
 '7h 50m',
 '5h 55m',
 '8h 25m',
 '6h 00m',
 '7h 30m',
 '4h 45m',
 '9h 05m',
 '13h 00m',
 '6h 15m',
 '8h 25m',
 '4h 30m',
 '11h 10m',
 '5h 15m',
 '11h 30m',
 '5h 15m',
 '11h 50m',
 '6h 50m',
 '6h 50m',
 '8h 10m',
 '6h 55m',
 '8h 50m',
 '4h 45m',
 '6h 40m',
 '9h 25m',
 '6h 10m',
 '5h 15m',
 '6h 35m',
 '10h 10m',
 '5h 00m',
 '2h 40m',
 '4h 30m',
 '5h 10m',
 '7h 15m']

In [92]:
cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

154

In [93]:
price=[]
for i in cost:
    price.append(i.text)
price

['5,230',
 '5,230',
 '5,236',
 '5,236',
 '5,236',
 '5,236',
 '5,250',
 '5,250',
 '5,449',
 '5,449',
 '5,560',
 '5,560',
 '5,634',
 '5,658',
 '5,658',
 '5,658',
 '5,658',
 '5,658',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,659',
 '5,685',
 '5,685',
 '5,763',
 '5,763',
 '5,763',
 '5,763',
 '5,869',
 '6,058',
 '6,156',
 '6,603',
 '6,603',
 '6,603',
 '6,603',
 '6,603',
 '6,603',
 '6,603',
 '7,013',
 '7,142',
 '7,329',
 '7,346',
 '7,346',
 '7,884',
 '7,884',
 '8,215',
 '8,215',
 '8,215',
 '8,215',
 '8,493',
 '8,781',
 '8,781',
 '8,855',
 '8,855',
 '8,997',
 '9,126',
 '9,126',
 '9,126',
 '9,259',
 '9,322',
 '9,367',
 '9,367',
 '9,532',
 '9,532',
 '9,532',
 '9,532',
 '9,532',
 '9,532',
 '9,532',
 '9,532',
 '9,532',
 '9,665',
 '9,694',
 '9,725',
 '9,725',
 '9,725',
 '9,725',
 '9,725',
 '9,725',
 '9,725',
 '9,725',
 '9,725',
 '9,726',
 '9,726',
 '9,726',
 '9,726',
 '9,726',
 '9,726',
 '9,726',
 '9,726',
 '9,726',
 '9,726',
 '9,879',
 '9,884',
 '10,108',
 '10,196',
 '10,278',
 '10,278',
 '10,278',
 '10,278',
 '10,593',
 '10,593',
 '10,804',
 '10,829',
 '10,829',
 '10,851',
 '10,851',
 '11,044',
 '11,097',
 '11,340',
 '11,340',
 '11,340',
 '11,434',
 '11,479',
 '11,479',
 '11,727',
 '11,727',
 '12,086',
 '12,094',
 '12,094',
 '12,199',
 '12,252',
 '12,561',
 '12,792',
 '13,722',
 '14,608',
 '14,877',
 '14,929',
 '15,159',
 '15,319',
 '15,349',
 '15,532',
 '16,242',
 '16,609',
 '17,463',
 '18,783',
 '18,946',
 '20,571',
 '20,571',
 '20,914',
 '21,439',
 '21,754',
 '22,227',
 '24,201',
 '24,201']

In [94]:
add_info=driver.find_elements("xpath",'//span[@class="text"]')
len(add_info)

74

In [95]:
Add_info=[]
for i in add_info:
    Add_info.append(i.text)
Add_info

['Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal']

In [96]:
flights1 = pd.DataFrame({})
flights1['Airline'] = Airline
flights1['Destination'] = list1
flights1['Source'] = list2
flights1['Arrival_time'] = Arr_t
flights1['Departure_time'] =Dep_t
flights1['Total_Stops']=Total_s
flights1['Total_Duration']=duration
flights1['Additional_Info']=pd.Series(Add_info)
flights1['Price']=price
flights1

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,SpiceJet,New Delhi,Bangalore,18:30,21:15,Non Stop,2h 45m,Free Meal,"5,230"
1,SpiceJet,New Delhi,Bangalore,23:00,01:45\n+ 1 day,Non Stop,2h 45m,Free Meal,"5,230"
2,Vistara,New Delhi,Bangalore,21:10,23:45,Non Stop,2h 35m,Free Meal,"5,236"
3,Air Asia,New Delhi,Bangalore,22:40,01:25\n+ 1 day,Non Stop,2h 45m,Free Meal,"5,236"
4,IndiGo,New Delhi,Bangalore,20:40,23:35,Non Stop,2h 55m,Free Meal,"5,236"
...,...,...,...,...,...,...,...,...,...
149,IndiGo,New Delhi,Bangalore,15:15,20:15,1 Stop,5h 00m,NaN,"21,439"
150,Vistara,New Delhi,Bangalore,17:50,20:30,Non Stop,2h 40m,NaN,"21,754"
151,Go First,New Delhi,Bangalore,15:50,20:20,1 Stop,4h 30m,NaN,"22,227"
152,Vistara,New Delhi,Bangalore,09:40,14:50,1 Stop,5h 10m,NaN,"24,201"
153,Vistara,New Delhi,Bangalore,09:40,16:55,1 Stop,7h 15m,NaN,"24,201"

In [97]:
Flight1=pd.concat([flights, flights1], ignore_index=True)

In [98]:
Flight1.shape

(311, 9)

### Scrapping data for Delhi to Hydrabad Loacation

In [100]:
# Connecting to the webdriver.

driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [101]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=HYD&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1008032076741'
driver.get(url)

In [103]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)

105

In [104]:
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

['SpiceJet',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Go First',
 'IndiGo',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air Asia',
 'IndiGo',
 'Air India',
 'Air India',
 'Air Asia',
 'Air Asia',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Air Asia',
 'Air Asia',
 'IndiGo',
 'Vistara',
 'Air Asia',
 'Air Asia',
 'IndiGo',
 'Vistara',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara']

In [105]:
flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

105

In [106]:
Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

['SG-8165',
 'AI-560',
 'AI-544',
 'AI-542',
 '6E-6203',
 '6E-2461',
 'G8-422',
 '6E-774',
 'UK-829',
 '6E-6605',
 '6E-2004',
 '6E-2187',
 '6E-2005',
 '6E-6371',
 'I5-743/1543',
 'UK-871',
 'UK-859',
 'UK-899',
 '6E-2212',
 'UK-879',
 '6E-2076/679',
 'UK-807/897',
 'UK-811/897',
 'I5-740/1228',
 'I5-740/1983',
 'I5-740/972',
 'UK-811/893',
 '6E-2208/752',
 '6E-2596',
 'AI-504/516',
 'AI-815/516',
 'AI-506/516',
 'AI-1506/516',
 'AI-807/516',
 'AI-803/516',
 'AI-814/615',
 'AI-605/615',
 'AI-805/615',
 'AI-678/615',
 'AI-865/615',
 'AI-665/615',
 'AI-887/615',
 '6E-2423/814',
 '6E-2042/752',
 'UK-809/897',
 'UK-819/897',
 'UK-815/897',
 'AI-441/615',
 'AI-512/516',
 'AI-813/516',
 'UK-819/893',
 'UK-815/893',
 'UK-627/614/869',
 'UK-627/626/869',
 'UK-635/626/869',
 'I5-1228',
 '6E-204/7249',
 'AI-624/615',
 'AI-863/615',
 'I5-1228/1983',
 'I5-1228/972',
 'UK-807/893',
 'UK-627/614/875',
 'UK-627/626/875',
 'UK-635/626/875',
 '6E-6231/511',
 '6E-2092/7249',
 'UK-981/869',
 'UK-981/875',
 'UK-955/875',
 'UK-809/893',
 'SG-8946/2926',
 'UK-855/556/869',
 'UK-801/897',
 '6E-2319/278',
 '6E-7148/278',
 '6E-2427/278',
 'UK-855/556/875',
 'UK-981/873',
 'UK-985/873',
 'UK-955/873',
 'UK-933/873',
 'UK-951/873',
 'UK-993/873',
 'SG-8946/4006',
 'UK-801/893',
 'UK-847/882/893',
 '6E-2216/511',
 'I5-745/1518',
 'I5-745/974',
 '6E-2216/6916',
 'UK-957/873',
 'I5-798/1518',
 'I5-798/974',
 '6E-2204/471',
 'UK-813/897',
 'AI-401/526',
 'UK-975/877',
 'UK-817/897',
 'UK-943/877',
 'UK-981/877',
 'UK-985/877',
 'UK-957/877',
 'UK-977/873',
 'UK-941/873']

In [107]:
source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

210

In [108]:
sources=[]
for i in source:
    sources.append(i.text)
sources

['New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad',
 'New Delhi',
 'Hyderabad']

In [109]:
list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]

In [110]:
list1

['Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad',
 'Hyderabad']

In [111]:
list2=sources[::2]

In [112]:
list2

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [113]:
arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

105

In [114]:
Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

['16:25',
 '07:10',
 '16:50',
 '09:45',
 '06:30',
 '01:55',
 '21:45',
 '08:10',
 '07:20',
 '19:45',
 '13:40',
 '15:10',
 '09:55',
 '21:25',
 '04:55',
 '20:40',
 '10:20',
 '14:45',
 '17:15',
 '17:35',
 '06:45',
 '20:40',
 '05:35',
 '08:10',
 '08:10',
 '08:10',
 '05:35',
 '22:45',
 '20:00',
 '21:10',
 '15:35',
 '09:45',
 '18:10',
 '17:00',
 '06:10',
 '22:30',
 '21:20',
 '20:00',
 '10:10',
 '10:00',
 '08:00',
 '07:00',
 '07:30',
 '20:30',
 '19:55',
 '14:10',
 '08:10',
 '17:50',
 '19:25',
 '08:00',
 '14:10',
 '08:10',
 '13:20',
 '13:20',
 '11:00',
 '09:30',
 '11:45',
 '19:00',
 '14:00',
 '09:30',
 '09:30',
 '20:40',
 '13:20',
 '13:20',
 '11:00',
 '05:15',
 '15:35',
 '21:40',
 '21:40',
 '17:45',
 '19:55',
 '12:45',
 '18:40',
 '09:05',
 '16:15',
 '14:55',
 '13:30',
 '18:40',
 '21:40',
 '19:45',
 '17:45',
 '15:30',
 '14:20',
 '12:50',
 '12:45',
 '09:05',
 '11:10',
 '09:25',
 '13:15',
 '13:15',
 '09:25',
 '20:40',
 '12:45',
 '12:45',
 '13:00',
 '17:30',
 '06:50',
 '05:45',
 '16:05',
 '07:30',
 '21:40',
 '19:45',
 '20:40',
 '19:00',
 '16:35']

In [115]:
dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

105

In [116]:
Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t

['18:45',
 '09:20',
 '19:00',
 '12:00',
 '08:50',
 '04:15',
 '23:55',
 '10:30',
 '09:25',
 '22:00',
 '15:50',
 '17:25',
 '12:15',
 '23:50',
 '13:45',
 '22:45',
 '12:35',
 '17:00',
 '19:35',
 '19:50',
 '15:45',
 '08:10\n+ 1 day',
 '08:10\n+ 1 day',
 '14:05',
 '16:50',
 '17:20',
 '19:55',
 '06:55\n+ 1 day',
 '22:15',
 '08:40\n+ 1 day',
 '08:40\n+ 1 day',
 '08:40\n+ 1 day',
 '08:40\n+ 1 day',
 '08:40\n+ 1 day',
 '08:40\n+ 1 day',
 '07:25\n+ 1 day',
 '07:25\n+ 1 day',
 '07:25\n+ 1 day',
 '07:25\n+ 1 day',
 '07:25\n+ 1 day',
 '07:25\n+ 1 day',
 '07:25\n+ 1 day',
 '12:45',
 '06:55\n+ 1 day',
 '08:10\n+ 1 day',
 '08:10\n+ 1 day',
 '08:10\n+ 1 day',
 '07:25\n+ 1 day',
 '08:40\n+ 1 day',
 '08:40\n+ 1 day',
 '19:55',
 '19:55',
 '00:05\n+ 2 days',
 '00:05\n+ 2 days',
 '00:05\n+ 2 days',
 '14:05',
 '22:25',
 '07:25\n+ 1 day',
 '07:25\n+ 1 day',
 '16:50',
 '17:20',
 '20:45\n+ 1 day',
 '20:55\n+ 1 day',
 '20:55\n+ 1 day',
 '20:55\n+ 1 day',
 '13:45',
 '22:25',
 '00:05\n+ 2 days',
 '20:55\n+ 1 day',
 '20:55\n+ 1 day',
 '20:45\n+ 1 day',
 '18:00',
 '00:05\n+ 2 days',
 '08:10\n+ 1 day',
 '21:35',
 '21:35',
 '21:35',
 '20:55\n+ 1 day',
 '07:45\n+ 1 day',
 '07:45\n+ 1 day',
 '07:45\n+ 1 day',
 '07:45\n+ 1 day',
 '07:45\n+ 1 day',
 '07:45\n+ 1 day',
 '13:35\n+ 1 day',
 '19:55',
 '19:55',
 '13:45',
 '20:25',
 '21:05',
 '18:45',
 '07:45\n+ 1 day',
 '20:25',
 '21:05',
 '19:15',
 '08:10\n+ 1 day',
 '21:15',
 '12:15',
 '08:10\n+ 1 day',
 '12:15',
 '12:15\n+ 1 day',
 '12:15\n+ 1 day',
 '12:15\n+ 1 day',
 '07:45\n+ 1 day',
 '07:45\n+ 1 day']

In [117]:
duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

105

In [118]:
Duration=[]
for i in duration_tag:
    Duration.append(i.text)
Duration

['2h 20m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '2h 20m',
 '2h 20m',
 '2h 10m',
 '2h 20m',
 '2h 05m',
 '2h 15m',
 '2h 10m',
 '2h 15m',
 '2h 20m',
 '2h 25m',
 '8h 50m',
 '2h 05m',
 '2h 15m',
 '2h 15m',
 '2h 20m',
 '2h 15m',
 '9h 00m',
 '11h 30m',
 '26h 35m',
 '5h 55m',
 '8h 40m',
 '9h 10m',
 '14h 20m',
 '8h 10m',
 '2h 15m',
 '11h 30m',
 '17h 05m',
 '22h 55m',
 '14h 30m',
 '15h 40m',
 '26h 30m',
 '8h 55m',
 '10h 05m',
 '11h 25m',
 '21h 15m',
 '21h 25m',
 '23h 25m',
 '24h 25m',
 '5h 15m',
 '10h 25m',
 '12h 15m',
 '18h 00m',
 '24h 00m',
 '13h 35m',
 '13h 15m',
 '24h 40m',
 '5h 45m',
 '11h 45m',
 '34h 45m',
 '34h 45m',
 '37h 05m',
 '4h 35m',
 '10h 40m',
 '12h 25m',
 '17h 25m',
 '7h 20m',
 '7h 50m',
 '24h 05m',
 '31h 35m',
 '31h 35m',
 '33h 55m',
 '8h 30m',
 '6h 50m',
 '26h 25m',
 '23h 15m',
 '27h 10m',
 '24h 50m',
 '5h 15m',
 '29h 25m',
 '23h 05m',
 '5h 20m',
 '6h 40m',
 '8h 05m',
 '26h 15m',
 '10h 05m',
 '12h 00m',
 '14h 00m',
 '16h 15m',
 '17h 25m',
 '18h 55m',
 '24h 50m',
 '10h 50m',
 '8h 45m',
 '4h 20m',
 '7h 10m',
 '7h 50m',
 '9h 20m',
 '11h 05m',
 '7h 40m',
 '8h 20m',
 '6h 15m',
 '14h 40m',
 '14h 25m',
 '6h 30m',
 '16h 05m',
 '4h 45m',
 '14h 35m',
 '16h 30m',
 '15h 35m',
 '12h 45m',
 '15h 10m']

In [119]:
total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

105

In [120]:
Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s

['Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop']

In [121]:
cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

105

In [122]:
price=[]
for i in cost:
    price.append(i.text)
price

['5,182',
 '5,184',
 '5,184',
 '5,184',
 '5,184',
 '5,394',
 '5,453',
 '5,604',
 '5,955',
 '6,269',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,319',
 '7,320',
 '7,320',
 '7,320',
 '7,424',
 '7,635',
 '7,870',
 '8,286',
 '8,286',
 '8,548',
 '8,548',
 '8,548',
 '9,021',
 '9,307',
 '9,419',
 '9,441',
 '9,441',
 '9,441',
 '9,704',
 '9,704',
 '9,704',
 '9,840',
 '9,840',
 '9,840',
 '9,840',
 '9,840',
 '9,840',
 '9,840',
 '10,114',
 '10,147',
 '10,229',
 '10,229',
 '10,229',
 '10,365',
 '10,544',
 '10,544',
 '10,964',
 '10,964',
 '10,971',
 '10,971',
 '10,971',
 '10,995',
 '11,059',
 '11,205',
 '11,205',
 '11,206',
 '11,206',
 '11,226',
 '11,266',
 '11,266',
 '11,266',
 '11,422',
 '11,479',
 '12,044',
 '12,255',
 '12,255',
 '13,169',
 '13,268',
 '13,333',
 '13,379',
 '13,383',
 '13,383',
 '13,383',
 '13,628',
 '13,830',
 '13,830',
 '13,830',
 '13,830',
 '13,830',
 '13,830',
 '14,004',
 '14,114',
 '14,857',
 '14,991',
 '15,183',
 '15,183',
 '16,220',
 '16,665',
 '17,110',
 '17,110',
 '20,017',
 '21,390',
 '21,600',
 '24,015',
 '24,540',
 '24,960',
 '24,960',
 '24,960',
 '27,795',
 '33,854',
 '33,854']

In [123]:
Add_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(Add_tag)

67

In [124]:
Add_info=[]
for i in Add_tag:
    Add_info.append(i.text)
Add_info

['Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal']

In [125]:
flights2 = pd.DataFrame({})
flights2['Airline'] = Airline
flights2['Destination'] = list1
flights2['Source'] = list2
flights2['Arrival_time'] = Arr_t
flights2['Departure_time'] =Dep_t
flights2['Total_Stops']=Total_s
flights2['Total_Duration']=Duration
flights2['Additional_Info']=pd.Series(Add_info)
flights2['Price']=price
flights2

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,SpiceJet,Hyderabad,New Delhi,16:25,18:45,Non Stop,2h 20m,Free Meal,"5,182"
1,Air India,Hyderabad,New Delhi,07:10,09:20,Non Stop,2h 10m,Free Meal,"5,184"
2,Air India,Hyderabad,New Delhi,16:50,19:00,Non Stop,2h 10m,Free Meal,"5,184"
3,Air India,Hyderabad,New Delhi,09:45,12:00,Non Stop,2h 15m,Free Meal,"5,184"
4,IndiGo,Hyderabad,New Delhi,06:30,08:50,Non Stop,2h 20m,Free Meal,"5,184"
...,...,...,...,...,...,...,...,...,...
100,Vistara,Hyderabad,New Delhi,21:40,12:15\n+ 1 day,1 Stop,14h 35m,NaN,"24,960"
101,Vistara,Hyderabad,New Delhi,19:45,12:15\n+ 1 day,1 Stop,16h 30m,NaN,"24,960"
102,Vistara,Hyderabad,New Delhi,20:40,12:15\n+ 1 day,1 Stop,15h 35m,NaN,"27,795"
103,Vistara,Hyderabad,New Delhi,19:00,07:45\n+ 1 day,1 Stop,12h 45m,NaN,"33,854"
104,Vistara,Hyderabad,New Delhi,16:35,07:45\n+ 1 day,1 Stop,15h 10m,NaN,"33,854"

In [126]:
# Connecting to the webdriver.

driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [127]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=GOI&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=938261628504'
driver.get(url)

In [129]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)

137

In [130]:
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

['SpiceJet',
 'SpiceJet',
 'Go First',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Air India',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Air India',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Air India',
 'IndiGo',
 'IndiGo',
 'SpiceJet',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Air Asia',
 'Air India',
 'Vistara',
 'IndiGo',
 'Go First',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air Asia',
 'Air Asia',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Air Asia',
 'Air India',
 'Air India',
 'Vistara',
 'Go First',
 'Air Asia',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Air Asia',
 'IndiGo',
 'Air India',
 'Air Asia',
 'SpiceJet',
 'SpiceJet',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Air Asia',
 'Air Asia',
 'Vistara',
 'SpiceJet',
 'IndiGo',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet']

In [131]:
flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

137

In [132]:
Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

['SG-8701/220',
 'SG-8244/220',
 'G8-194',
 'SG-8701/488',
 'SG-8701/455',
 'SG-8244/488',
 'SG-8244/455',
 'SG-8169/455',
 'SG-8709/455',
 'UK-855',
 'AI-883',
 'I5-1732/1574',
 'I5-1732/818',
 'I5-779',
 'I5-773',
 'G8-334/331',
 'G8-530/331',
 'G8-354/575',
 'G8-336/384',
 'G8-330/575',
 'G8-334/382',
 'G8-2501/331',
 'G8-346/575',
 'G8-334/371',
 'G8-530/382',
 'G8-530/371',
 'G8-323/575',
 '6E-2519/5202',
 '6E-2089',
 '6E-2028',
 'UK-847',
 'AI-506/893',
 'UK-811/881',
 'UK-807/881',
 '6E-2263',
 'UK-975/555',
 'AI-803/893',
 '6E-2505/6809',
 '6E-5044',
 'SG-8165/4007',
 'AI-678/683',
 'AI-665/683',
 'AI-887/683',
 'AI-814/683',
 'AI-605/683',
 '6E-2329',
 'SG-8169/488',
 'SG-8709/488',
 'SG-8165/4001',
 '6E-864/5206',
 '6E-5318/5206',
 '6E-2016/5206',
 '6E-6601/763',
 'AI-441/683',
 '6E-6203/905',
 'UK-955/555',
 'UK-933/555',
 'UK-951/555',
 'UK-993/555',
 'UK-945/555',
 'UK-995/555',
 'UK-927/555',
 'UK-963/555',
 'UK-943/555',
 'AI-813/893',
 'I5-548/745',
 'AI-885',
 'UK-975/843',
 '6E-2212/6532',
 'G8-286',
 '6E-2042/6981',
 '6E-774/905',
 '6E-2138/6809',
 '6E-2187/984',
 'AI-678/663',
 'AI-665/663',
 'AI-887/663',
 'AI-863/683',
 'I5-740/1453',
 'I5-857/1574',
 'UK-815/881',
 'UK-809/881',
 'UK-819/881',
 '6E-308/6653',
 'UK-955/843',
 'UK-933/843',
 'UK-951/843',
 'UK-993/843',
 'UK-945/843',
 'UK-995/843',
 'UK-927/843',
 'UK-963/843',
 'UK-975/841',
 'SG-3755/3704',
 'AI-605/685',
 'AI-805/685',
 '6E-5218/179',
 '6E-2075/179',
 'I5-798',
 'I5-745',
 'AI-441/685',
 'AI-475/646/683',
 'UK-943/841',
 'G8-113/285',
 'I5-1228/972',
 'AI-624/685',
 'AI-863/685',
 '6E-2092/885',
 '6E-6814/179',
 'UK-801/881',
 'I5-1228/1983',
 '6E-2216/6219',
 'AI-473/670/683',
 'I5-711/1453',
 'SG-8722',
 'SG-8411',
 'AI-605/663',
 'AI-805/663',
 'UK-787/546/843',
 'UK-787/546/555',
 'UK-785/546/843',
 'UK-785/546/555',
 'UK-985/555',
 'UK-781/546/843',
 'UK-781/546/555',
 'AI-624/663',
 'UK-781/544/843',
 'I5-1228/1983',
 'I5-1228/972',
 'UK-929/918/843',
 'SG-8938/525',
 '6E-6261/117',
 'SG-8496',
 'UK-813/881',
 'UK-817/881',
 'UK-941/843',
 'SG-3701/3704']

In [133]:
source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

274

In [134]:
sources=[]
for i in source:
    sources.append(i.text)
sources

['New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa',
 'New Delhi',
 'Goa']

In [135]:
list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]

In [136]:
list1

['Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa']

In [137]:
list2=sources[::2]

In [138]:
list2

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [139]:
arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

137

In [140]:
Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

['06:45',
 '02:00',
 '21:30',
 '06:45',
 '06:45',
 '02:00',
 '02:00',
 '20:00',
 '18:10',
 '18:40',
 '22:00',
 '21:20',
 '21:20',
 '04:35',
 '20:00',
 '07:20',
 '06:00',
 '22:30',
 '14:35',
 '21:00',
 '07:20',
 '02:40',
 '20:00',
 '07:20',
 '06:00',
 '06:00',
 '18:00',
 '23:00',
 '09:55',
 '16:25',
 '11:10',
 '09:45',
 '05:35',
 '20:40',
 '19:10',
 '05:45',
 '06:10',
 '11:00',
 '12:05',
 '16:25',
 '10:10',
 '08:00',
 '07:00',
 '22:30',
 '21:20',
 '10:55',
 '20:00',
 '18:10',
 '16:25',
 '17:25',
 '16:25',
 '15:45',
 '20:10',
 '17:50',
 '06:30',
 '17:45',
 '15:30',
 '14:20',
 '12:50',
 '11:40',
 '10:20',
 '09:30',
 '08:50',
 '07:30',
 '08:00',
 '07:10',
 '10:55',
 '05:45',
 '17:15',
 '10:55',
 '20:30',
 '08:10',
 '12:00',
 '15:10',
 '10:10',
 '08:00',
 '07:00',
 '14:00',
 '08:10',
 '19:05',
 '08:10',
 '19:55',
 '14:10',
 '07:55',
 '17:45',
 '15:30',
 '14:20',
 '12:50',
 '11:40',
 '10:20',
 '09:30',
 '08:50',
 '05:45',
 '17:00',
 '21:20',
 '20:00',
 '06:30',
 '08:10',
 '12:45',
 '13:15',
 '17:50',
 '12:55',
 '07:30',
 '05:45',
 '09:30',
 '19:00',
 '14:00',
 '15:35',
 '07:15',
 '09:05',
 '09:30',
 '09:25',
 '18:40',
 '05:45',
 '12:00',
 '17:45',
 '21:20',
 '20:00',
 '10:20',
 '10:20',
 '06:55',
 '06:55',
 '19:45',
 '17:50',
 '17:50',
 '19:00',
 '17:50',
 '09:30',
 '09:30',
 '21:20',
 '17:35',
 '10:55',
 '16:50',
 '17:30',
 '16:05',
 '16:35',
 '06:45']

In [141]:
dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

137

In [142]:
Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t

['22:20',
 '22:20',
 '00:05\n+ 1 day',
 '12:30',
 '16:30',
 '12:30',
 '16:30',
 '16:30\n+ 1 day',
 '16:30\n+ 1 day',
 '21:20',
 '00:40\n+ 1 day',
 '05:25\n+ 1 day',
 '06:45\n+ 1 day',
 '07:25',
 '22:35',
 '12:45',
 '12:45',
 '06:10\n+ 1 day',
 '23:25',
 '06:10\n+ 1 day',
 '16:35',
 '12:45',
 '06:10\n+ 1 day',
 '17:45',
 '16:35',
 '17:45',
 '06:10\n+ 1 day',
 '06:10\n+ 1 day',
 '12:35',
 '19:05',
 '13:50',
 '17:45',
 '14:05',
 '14:05\n+ 1 day',
 '21:55',
 '00:05\n+ 1 day',
 '17:45',
 '18:15',
 '14:40',
 '18:10\n+ 1 day',
 '22:20',
 '22:20',
 '22:20',
 '22:20\n+ 1 day',
 '22:20\n+ 1 day',
 '13:40',
 '12:30\n+ 1 day',
 '12:30\n+ 1 day',
 '07:10\n+ 1 day',
 '23:10',
 '23:10',
 '23:10',
 '01:35\n+ 1 day',
 '22:20',
 '13:55',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '00:05\n+ 1 day',
 '17:45',
 '17:35',
 '13:25',
 '22:10',
 '00:20\n+ 1 day',
 '13:30',
 '01:30\n+ 1 day',
 '13:55',
 '18:15',
 '21:35',
 '14:45',
 '14:45',
 '14:45',
 '22:20',
 '14:15',
 '05:25\n+ 1 day',
 '14:05',
 '14:05\n+ 1 day',
 '14:05\n+ 1 day',
 '14:35',
 '22:10',
 '22:10',
 '22:10',
 '22:10',
 '22:10',
 '22:10',
 '22:10',
 '22:10',
 '12:45',
 '18:50\n+ 1 day',
 '06:20\n+ 1 day',
 '06:20\n+ 1 day',
 '12:30',
 '12:30',
 '15:25',
 '17:35',
 '06:20\n+ 1 day',
 '22:20\n+ 1 day',
 '12:45',
 '17:10',
 '19:20',
 '06:20\n+ 1 day',
 '06:20\n+ 1 day',
 '20:45',
 '12:30',
 '14:05',
 '18:45',
 '14:15',
 '22:20\n+ 1 day',
 '14:15',
 '14:35',
 '20:25',
 '14:45\n+ 1 day',
 '14:45\n+ 1 day',
 '22:10\n+ 1 day',
 '00:05\n+ 2 days',
 '22:10\n+ 1 day',
 '00:05\n+ 2 days',
 '00:05\n+ 1 day',
 '22:10\n+ 1 day',
 '00:05\n+ 2 days',
 '14:45\n+ 1 day',
 '22:10\n+ 1 day',
 '18:45',
 '19:20',
 '22:10\n+ 1 day',
 '13:25\n+ 1 day',
 '16:55',
 '19:15',
 '14:05\n+ 1 day',
 '14:05\n+ 1 day',
 '22:10',
 '18:50']

In [143]:
duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

137

In [144]:
Duration=[]
for i in duration_tag:
    Duration.append(i.text)
Duration

['15h 35m',
 '20h 20m',
 '2h 35m',
 '5h 45m',
 '9h 45m',
 '10h 30m',
 '14h 30m',
 '20h 30m',
 '22h 20m',
 '2h 40m',
 '2h 40m',
 '8h 05m',
 '9h 25m',
 '2h 50m',
 '2h 35m',
 '5h 25m',
 '6h 45m',
 '7h 40m',
 '8h 50m',
 '9h 10m',
 '9h 15m',
 '10h 05m',
 '10h 10m',
 '10h 25m',
 '10h 35m',
 '11h 45m',
 '12h 10m',
 '7h 10m',
 '2h 40m',
 '2h 40m',
 '2h 40m',
 '8h 00m',
 '8h 30m',
 '17h 25m',
 '2h 45m',
 '18h 20m',
 '11h 35m',
 '7h 15m',
 '2h 35m',
 '25h 45m',
 '12h 10m',
 '14h 20m',
 '15h 20m',
 '23h 50m',
 '25h 00m',
 '2h 45m',
 '16h 30m',
 '18h 20m',
 '14h 45m',
 '5h 45m',
 '6h 45m',
 '7h 25m',
 '5h 25m',
 '4h 30m',
 '7h 25m',
 '6h 20m',
 '8h 35m',
 '9h 45m',
 '11h 15m',
 '12h 25m',
 '13h 45m',
 '14h 35m',
 '15h 15m',
 '16h 35m',
 '9h 45m',
 '10h 25m',
 '2h 30m',
 '16h 25m',
 '7h 05m',
 '2h 35m',
 '5h 00m',
 '5h 45m',
 '6h 15m',
 '6h 25m',
 '4h 35m',
 '6h 45m',
 '7h 45m',
 '8h 20m',
 '6h 05m',
 '10h 20m',
 '5h 55m',
 '18h 10m',
 '23h 55m',
 '6h 40m',
 '4h 25m',
 '6h 40m',
 '7h 50m',
 '9h 20m',
 '10h 30m',
 '11h 50m',
 '12h 40m',
 '13h 20m',
 '7h 00m',
 '25h 50m',
 '9h 00m',
 '10h 20m',
 '6h 00m',
 '4h 20m',
 '2h 40m',
 '4h 20m',
 '12h 30m',
 '33h 25m',
 '5h 15m',
 '11h 25m',
 '9h 50m',
 '11h 20m',
 '16h 20m',
 '5h 10m',
 '5h 15m',
 '5h 00m',
 '9h 15m',
 '4h 50m',
 '27h 40m',
 '8h 30m',
 '2h 35m',
 '2h 40m',
 '17h 25m',
 '18h 45m',
 '35h 50m',
 '37h 45m',
 '39h 15m',
 '41h 10m',
 '4h 20m',
 '28h 20m',
 '30h 15m',
 '19h 45m',
 '28h 20m',
 '9h 15m',
 '9h 50m',
 '24h 50m',
 '19h 50m',
 '6h 00m',
 '2h 25m',
 '20h 35m',
 '22h 00m',
 '5h 35m',
 '12h 05m']

In [145]:
total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

137

In [146]:
Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s

['1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop']

In [147]:
cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

137

In [148]:
price=[]
for i in cost:
    price.append(i.text)
price

['6,268',
 '6,268',
 '6,504',
 '6,520',
 '6,520',
 '6,520',
 '6,520',
 '6,520',
 '6,520',
 '7,005',
 '7,005',
 '7,053',
 '7,053',
 '7,215',
 '7,529',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,713',
 '7,819',
 '8,159',
 '8,159',
 '8,160',
 '8,280',
 '8,286',
 '8,286',
 '8,350',
 '8,402',
 '8,542',
 '8,628',
 '8,650',
 '8,678',
 '8,790',
 '8,790',
 '8,790',
 '8,790',
 '8,790',
 '8,900',
 '8,955',
 '8,955',
 '9,096',
 '9,186',
 '9,186',
 '9,186',
 '9,242',
 '9,315',
 '9,325',
 '9,347',
 '9,347',
 '9,347',
 '9,347',
 '9,347',
 '9,347',
 '9,347',
 '9,347',
 '9,347',
 '9,382',
 '9,382',
 '9,420',
 '9,420',
 '9,569',
 '9,631',
 '9,695',
 '9,745',
 '9,836',
 '10,147',
 '10,155',
 '10,155',
 '10,155',
 '10,155',
 '10,156',
 '10,156',
 '10,229',
 '10,229',
 '10,229',
 '10,259',
 '10,365',
 '10,365',
 '10,365',
 '10,365',
 '10,365',
 '10,365',
 '10,365',
 '10,365',
 '10,575',
 '10,706',
 '10,785',
 '10,785',
 '11,097',
 '11,204',
 '11,309',
 '11,309',
 '11,310',
 '11,396',
 '11,520',
 '11,906',
 '11,962',
 '12,150',
 '12,150',
 '12,412',
 '12,464',
 '13,379',
 '13,646',
 '13,853',
 '13,970',
 '14,137',
 '14,144',
 '14,144',
 '14,880',
 '14,880',
 '15,193',
 '15,193',
 '15,193',
 '15,193',
 '15,857',
 '15,928',
 '15,928',
 '16,245',
 '16,883',
 '17,006',
 '17,006',
 '17,102',
 '17,765',
 '19,487',
 '19,500',
 '21,390',
 '24,540',
 '30,389',
 '38,555']

In [149]:
add_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(add_tag)

66

In [150]:
Add_info=[]
for i in add_tag:
    Add_info.append(i.text)
Add_info

['Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal']

In [151]:
flights3 = pd.DataFrame({})
flights3['Airline'] = Airline
flights3['Destination'] = list1
flights3['Source'] = list2
flights3['Arrival_time'] = Arr_t
flights3['Departure_time'] =Dep_t
flights3['Total_Stops']=Total_s
flights3['Total_Duration']=Duration
flights3['Additional_Info']=pd.Series(Add_info)
flights3['Price']=price
flights3

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,SpiceJet,Goa,New Delhi,06:45,22:20,1 Stop,15h 35m,Free Meal,"6,268"
1,SpiceJet,Goa,New Delhi,02:00,22:20,1 Stop,20h 20m,Free Meal,"6,268"
2,Go First,Goa,New Delhi,21:30,00:05\n+ 1 day,Non Stop,2h 35m,Free Meal,"6,504"
3,SpiceJet,Goa,New Delhi,06:45,12:30,1 Stop,5h 45m,Free Meal,"6,520"
4,SpiceJet,Goa,New Delhi,06:45,16:30,1 Stop,9h 45m,Free Meal,"6,520"
...,...,...,...,...,...,...,...,...,...
132,SpiceJet,Goa,New Delhi,16:50,19:15,Non Stop,2h 25m,NaN,"19,500"
133,Vistara,Goa,New Delhi,17:30,14:05\n+ 1 day,1 Stop,20h 35m,NaN,"21,390"
134,Vistara,Goa,New Delhi,16:05,14:05\n+ 1 day,1 Stop,22h 00m,NaN,"24,540"
135,Vistara,Goa,New Delhi,16:35,22:10,1 Stop,5h 35m,NaN,"30,389"
136,SpiceJet,Goa,New Delhi,06:45,18:50,1 Stop,12h 05m,NaN,"38,555"

In [155]:
Flight=pd.concat([flights,flights1,flights2,flights3],ignore_index=True)

In [156]:
Flight.shape

(553, 9)

In [157]:
Flight.head()

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,SpiceJet,Mumbai,New Delhi,20:10,10:30\n+ 1 day,1 Stop,14h 20m,Free Meal,"4,775"
1,Air Asia,Mumbai,New Delhi,04:55,13:05,1 Stop,8h 10m,Free Meal,"5,383"
2,Go First,Mumbai,New Delhi,02:40,04:50,Non Stop,2h 10m,Free Meal,"5,452"
3,Go First,Mumbai,New Delhi,06:00,08:10,Non Stop,2h 10m,Free Meal,"5,452"
4,Go First,Mumbai,New Delhi,07:20,09:30,Non Stop,2h 10m,Free Meal,"5,452"

In [169]:
# Connecting to the webdriver.

driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [170]:
# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=MAA&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=330436760794'
driver.get(url)

In [172]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

['Go First',
 'Go First',
 'Go First',
 'Go First',
 'SpiceJet',
 'Air Asia',
 'Air Asia',
 'IndiGo',
 'SpiceJet',
 'SpiceJet',
 'Air India',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Air India',
 'Air India',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Air India',
 'Air India',
 'IndiGo',
 'Vistara',
 'Air Asia',
 'Air Asia',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Air India',
 'Air India',
 'SpiceJet',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'SpiceJet',
 'Air India',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara']

In [173]:
len(Airline)

105

In [174]:
flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights4 = pd.DataFrame({})
flights4['Airline'] = Airline
flights4['Destination'] = list1
flights4['Source'] = list2
flights4['Arrival_time'] = Arr_t
flights4['Departure_time'] =Dep_t
flights4['Total_Stops']=Total_s
flights4['Total_Duration']=duration
flights4['Additional_Info']=pd.Series(Add_info)
flights4['Price']=price
flights4

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,Go First,Chennai,New Delhi,22:30,07:35\n+ 1 day,1 Stop,9h 05m,Free Meal,"6,417"
1,Go First,Chennai,New Delhi,21:00,07:35\n+ 1 day,1 Stop,10h 35m,Free Meal,"6,417"
2,Go First,Chennai,New Delhi,20:00,07:35\n+ 1 day,1 Stop,11h 35m,Free Meal,"6,417"
3,Go First,Chennai,New Delhi,18:00,07:35\n+ 1 day,1 Stop,13h 35m,Free Meal,"6,417"
4,SpiceJet,Chennai,New Delhi,18:50,21:30,Non Stop,2h 40m,Free Meal,"6,610"
...,...,...,...,...,...,...,...,...,...
100,Vistara,Chennai,New Delhi,19:45,08:55\n+ 1 day,1 Stop,13h 10m,NaN,"22,125"
101,SpiceJet,Chennai,New Delhi,16:50,22:35,1 Stop,5h 45m,NaN,"22,912"
102,Vistara,Chennai,New Delhi,16:35,23:00,1 Stop,6h 25m,NaN,"35,639"
103,Vistara,Chennai,New Delhi,19:00,08:55\n+ 1 day,1 Stop,13h 55m,NaN,"35,639"
104,Vistara,Chennai,New Delhi,13:20,23:00,2 Stop(s),9h 40m,NaN,"49,425"

In [175]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [176]:
# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=CCU&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=435938972981'
driver.get(url)

In [177]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

['SpiceJet',
 'Vistara',
 'SpiceJet',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Vistara',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara']

In [178]:
flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights5 = pd.DataFrame({})
flights5['Airline'] = Airline
flights5['Destination'] = list1
flights5['Source'] = list2
flights5['Arrival_time'] = Arr_t
flights5['Departure_time'] =Dep_t
flights5['Total_Stops']=Total_s
flights5['Total_Duration']=duration
flights5['Additional_Info']=pd.Series(Add_info)
flights5['Price']=price
flights5

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,SpiceJet,Kolkata,New Delhi,20:35,22:50,Non Stop,2h 15m,Free Meal,"6,994"
1,Vistara,Kolkata,New Delhi,20:30,22:20,Non Stop,1h 50m,Free Meal,"7,005"
2,SpiceJet,Kolkata,New Delhi,14:15,10:25\n+ 1 day,1 Stop,20h 10m,Free Meal,"7,164"
3,Air Asia,Kolkata,New Delhi,15:05,02:30\n+ 1 day,1 Stop,11h 25m,Free Meal,"7,319"
4,Air Asia,Kolkata,New Delhi,20:40,08:10\n+ 1 day,1 Stop,11h 30m,Free Meal,"7,319"
...,...,...,...,...,...,...,...,...,...
77,Vistara,Kolkata,New Delhi,16:35,19:50\n+ 1 day,1 Stop,27h 15m,NaN,"37,634"
78,Vistara,Kolkata,New Delhi,19:00,16:50\n+ 1 day,1 Stop,21h 50m,NaN,"38,474"
79,Vistara,Kolkata,New Delhi,16:35,16:50\n+ 1 day,1 Stop,24h 15m,NaN,"38,474"
80,Vistara,Kolkata,New Delhi,19:00,09:40\n+ 1 day,1 Stop,14h 40m,NaN,"39,419"
81,Vistara,Kolkata,New Delhi,16:35,09:40\n+ 1 day,1 Stop,17h 05m,NaN,"39,419"

In [179]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [180]:
# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=PNQ&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1453607888647'
driver.get(url)

In [181]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights6 = pd.DataFrame({})
flights6['Airline'] = Airline
flights6['Destination'] = list1
flights6['Source'] = list2
flights6['Arrival_time'] = Arr_t
flights6['Departure_time'] =Dep_t
flights6['Total_Stops']=Total_s
flights6['Total_Duration']=duration
flights6['Additional_Info']=pd.Series(Add_info)
flights6['Price']=price
flights6

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,Go First,Pune,New Delhi,17:30,06:15\n+ 1 day,1 Stop,12h 45m,Free Meal,"6,873"
1,Air Asia,Pune,New Delhi,21:20,05:00\n+ 1 day,1 Stop,7h 40m,Free Meal,"6,984"
2,Vistara,Pune,New Delhi,20:50,22:55,Non Stop,2h 05m,Free Meal,"7,318"
3,Vistara,Pune,New Delhi,22:30,00:35\n+ 1 day,Non Stop,2h 05m,Free Meal,"7,318"
4,Air Asia,Pune,New Delhi,23:05,01:10\n+ 1 day,Non Stop,2h 05m,Free Meal,"7,319"
5,Go First,Pune,New Delhi,16:55,18:55,Non Stop,2h 00m,Free Meal,"7,323"
6,Go First,Pune,New Delhi,22:05,00:10\n+ 1 day,Non Stop,2h 05m,Free Meal,"7,323"
7,Vistara,Pune,New Delhi,17:25,19:40,Non Stop,2h 15m,Free Meal,"7,635"
8,Air Asia,Pune,New Delhi,16:30,05:00\n+ 1 day,1 Stop,12h 30m,Free Meal,"7,636"
9,IndiGo,Pune,New Delhi,13:25,15:40,Non Stop,2h 15m,Free Meal,"7,844"
10,Air Asia,Pune,New Delhi,15:05,17:15,Non Stop,2h 10m,Free Meal,"7,875"
11,Vistara,Pune,New Delhi,13:45,15:55,Non Stop,2h 10m,Free Meal,"8,055"
12,Go First,Pune,New Delhi,18:30,20:20,Non Stop,1h 50m,Free Meal,"8,057"
13,IndiGo,Pune,New Delhi,21:10,23:10,Non Stop,2h 00m,Free Meal,"8,159"
14,IndiGo,Pune,New Delhi,23:15,01:20\n+ 1 day,Non Stop,2h 05m,Free Meal,"8,159"
15,IndiGo,Pune,New Delhi,19:45,05:45\n+ 1 day,1 Stop,10h 00m,Free Meal,"9,175"
16,IndiGo,Pune,New Delhi,20:10,01:05\n+ 1 day,1 Stop,4h 55m,Free Meal,"9,734"
17,IndiGo,Pune,New Delhi,20:10,05:30\n+ 1 day,1 Stop,9h 20m,NaN,"9,734"
18,Air Asia,Pune,New Delhi,19:05,05:00\n+ 1 day,1 Stop,9h 55m,NaN,"10,049"
19,IndiGo,Pune,New Delhi,21:25,05:45\n+ 1 day,1 Stop,8h 20m,NaN,"10,225"
20,IndiGo,Pune,New Delhi,17:50,00:05\n+ 1 day,1 Stop,6h 15m,NaN,"10,894"
21,IndiGo,Pune,New Delhi,18:25,20:45,Non Stop,2h 20m,NaN,"10,994"
22,IndiGo,Pune,New Delhi,19:40,02:15\n+ 1 day,1 Stop,6h 35m,NaN,"11,729"
23,IndiGo,Pune,New Delhi,14:50,01:05\n+ 1 day,1 Stop,10h 15m,NaN,"12,162"
24,Vistara,Pune,New Delhi,20:40,07:55\n+ 1 day,1 Stop,11h 15m,NaN,"12,186"
25,IndiGo,Pune,New Delhi,23:40,04:10\n+ 1 day,1 Stop,4h 30m,NaN,"12,245"
26,IndiGo,Pune,New Delhi,17:40,00:25\n+ 1 day,1 Stop,6h 45m,NaN,"12,280"
27,IndiGo,Pune,New Delhi,16:15,00:05\n+ 1 day,1 Stop,7h 50m,NaN,"12,280"
28,IndiGo,Pune,New Delhi,14:55,00:05\n+ 1 day,1 Stop,9h 10m,NaN,"12,280"
29,IndiGo,Pune,New Delhi,20:00,05:45\n+ 1 day,1 Stop,9h 45m,NaN,"12,325"
30,IndiGo,Pune,New Delhi,19:10,00:05\n+ 1 day,1 Stop,4h 55m,NaN,"12,468"
31,SpiceJet,Pune,New Delhi,17:35,19:45,Non Stop,2h 10m,NaN,"12,515"
32,Air Asia,Pune,New Delhi,16:30,22:35,1 Stop,6h 05m,NaN,"13,382"
33,Vistara,Pune,New Delhi,17:30,07:55\n+ 1 day,1 Stop,14h 25m,NaN,"14,286"
34,Vistara,Pune,New Delhi,14:10,07:55\n+ 1 day,1 Stop,17h 45m,NaN,"14,286"
35,IndiGo,Pune,New Delhi,22:00,04:10\n+ 1 day,1 Stop,6h 10m,NaN,"15,310"
36,Vistara,Pune,New Delhi,13:45,07:55\n+ 1 day,2 Stop(s),18h 10m,NaN,"15,403"
37,IndiGo,Pune,New Delhi,20:20,04:10\n+ 1 day,1 Stop,7h 50m,NaN,"16,810"
38,Vistara,Pune,New Delhi,19:55,07:55\n+ 1 day,1 Stop,12h 00m,NaN,"16,911"
39,Vistara,Pune,New Delhi,14:10,22:05,1 Stop,7h 55m,NaN,"17,894"
40,IndiGo,Pune,New Delhi,17:15,22:00,1 Stop,4h 45m,NaN,"18,344"
41,SpiceJet,Pune,New Delhi,20:30,07:25\n+ 1 day,1 Stop,10h 55m,NaN,"18,870"
42,IndiGo,Pune,New Delhi,13:00,23:20,1 Stop,10h 20m,NaN,"18,974"
43,IndiGo,Pune,New Delhi,21:00,01:00\n+ 1 day,1 Stop,4h 00m,NaN,"19,251"
44,Vistara,Pune,New Delhi,20:40,22:05\n+ 1 day,1 Stop,25h 25m,NaN,"19,259"
45,Vistara,Pune,New Delhi,14:20,22:05,2 Stop(s),7h 45m,NaN,"21,107"
46,Vistara,Pune,New Delhi,14:20,22:05,2 Stop(s),7h 45m,NaN,"21,107"
47,Vistara,Pune,New Delhi,13:45,22:05,2 Stop(s),8h 20m,NaN,"22,125"
48,IndiGo,Pune,New Delhi,13:40,22:00,1 Stop,8h 20m,NaN,"22,229"
49,IndiGo,Pune,New Delhi,18:40,04:10\n+ 1 day,1 Stop,9h 30m,NaN,"22,410"
50,IndiGo,Pune,New Delhi,15:10,22:00,1 Stop,6h 50m,NaN,"23,069"
51,Vistara,Pune,New Delhi,19:55,22:05\n+ 1 day,1 Stop,26h 10m,NaN,"23,984"
52,Vistara,Pune,New Delhi,16:05,07:55\n+ 1 day,1 Stop,15h 50m,NaN,"25,447"
53,IndiGo,Pune,New Delhi,16:45,01:00\n+ 1 day,1 Stop,8h 15m,NaN,"25,551"
54,IndiGo,Pune,New Delhi,13:20,22:15,1 Stop,8h 55m,NaN,"26,085"
55,Vistara,Pune,New Delhi,16:05,22:05,1 Stop,6h 00m,NaN,"29,055"
56,SpiceJet,Pune,New Delhi,20:30,19:30\n+ 1 day,1 Stop,23h 00m,NaN,"31,063"

In [182]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

In [184]:
# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=LKO&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=818888982302'
driver.get(url)

In [185]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights7 = pd.DataFrame({})
flights7['Airline'] = Airline
flights7['Destination'] = list1
flights7['Source'] = list2
flights7['Arrival_time'] = Arr_t
flights7['Departure_time'] =Dep_t
flights7['Total_Stops']=Total_s
flights7['Total_Duration']=duration
flights7['Additional_Info']=pd.Series(Add_info)
flights7['Price']=price
flights7

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,IndiGo,Lucknow,New Delhi,17:50,19:00,Non Stop,1h 10m,Free Meal,"3,015"
1,IndiGo,Lucknow,New Delhi,21:30,22:40,Non Stop,1h 10m,Free Meal,"3,015"
2,Air Asia,Lucknow,New Delhi,21:45,22:55,Non Stop,1h 10m,No Meal Fare,"3,016"
3,Air India,Lucknow,New Delhi,12:30,13:30,Non Stop,1h 00m,Free Meal,"3,225"
4,IndiGo,Lucknow,New Delhi,19:10,20:15,Non Stop,1h 05m,Free Meal,"4,589"
5,IndiGo,Lucknow,New Delhi,16:15,17:25,Non Stop,1h 10m,Free Meal,"4,589"
6,Air India,Lucknow,New Delhi,18:40,19:45,Non Stop,1h 05m,Free Meal,"4,590"
7,IndiGo,Lucknow,New Delhi,14:55,16:25,Non Stop,1h 30m,Free Meal,"4,904"
8,Alliance Air,Lucknow,New Delhi,14:00,16:50,1 Stop,2h 50m,Free Meal,"5,430"
9,IndiGo,Lucknow,New Delhi,13:30,14:45,Non Stop,1h 15m,Free Meal,"5,954"
10,IndiGo,Lucknow,New Delhi,12:30,16:50,1 Stop,4h 20m,Free Meal,"10,317"
11,Vistara,Lucknow,New Delhi,13:35,14:50,Non Stop,1h 15m,Free Meal,"10,890"
12,Air India,Lucknow,New Delhi,22:30,13:20\n+ 1 day,1 Stop,14h 50m,Free Meal,"13,935"
13,Air India,Lucknow,New Delhi,21:20,13:20\n+ 1 day,1 Stop,16h 00m,Free Meal,"13,935"
14,Air India,Lucknow,New Delhi,20:00,13:20\n+ 1 day,1 Stop,17h 20m,Free Meal,"13,935"
15,Air India,Lucknow,New Delhi,19:00,13:20\n+ 1 day,1 Stop,18h 20m,NaN,"13,935"
16,Air India,Lucknow,New Delhi,11:35,13:20\n+ 1 day,1 Stop,25h 45m,NaN,"13,935"
17,Air India,Lucknow,New Delhi,17:50,13:20\n+ 1 day,1 Stop,19h 30m,NaN,"14,460"
18,Air India,Lucknow,New Delhi,14:00,13:20\n+ 1 day,1 Stop,23h 20m,NaN,"15,300"
19,Air India,Lucknow,New Delhi,21:10,13:20\n+ 1 day,2 Stop(s),16h 10m,NaN,"18,912"
20,Air India,Lucknow,New Delhi,22:00,13:20\n+ 1 day,2 Stop(s),15h 20m,NaN,"19,815"
21,Air India,Lucknow,New Delhi,20:40,13:20\n+ 1 day,2 Stop(s),16h 40m,NaN,"21,141"
22,Air India,Lucknow,New Delhi,20:40,13:20\n+ 1 day,2 Stop(s),16h 40m,NaN,"26,976"

In [186]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BOM&originCountry=IN&destination=PNQ&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=993545480401'
driver.get(url)

In [187]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights8 = pd.DataFrame({})
flights8['Airline'] = Airline
flights8['Destination'] = list1
flights8['Source'] = list2
flights8['Arrival_time'] = Arr_t
flights8['Departure_time'] =Dep_t
flights8['Total_Stops']=Total_s
flights8['Total_Duration']=duration
flights8['Additional_Info']=pd.Series(Add_info)
flights8['Price']=price
flights8

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,Go First,Pune,Mumbai,22:15,08:00\n+ 1 day,1 Stop,9h 45m,Free Meal,"6,261"
1,Go First,Pune,Mumbai,19:15,08:00\n+ 1 day,1 Stop,12h 45m,Free Meal,"6,762"
2,Go First,Pune,Mumbai,23:30,06:15\n+ 1 day,1 Stop,6h 45m,Free Meal,"6,855"
3,Go First,Pune,Mumbai,18:50,06:50\n+ 1 day,1 Stop,12h 00m,Free Meal,"6,855"
4,Vistara,Pune,Mumbai,21:30,07:55\n+ 1 day,1 Stop,10h 25m,Free Meal,"10,557"
5,Vistara,Pune,Mumbai,17:55,07:55\n+ 1 day,1 Stop,14h 00m,Free Meal,"10,557"
6,Vistara,Pune,Mumbai,17:30,07:55\n+ 1 day,1 Stop,14h 25m,Free Meal,"10,557"
7,Go First,Pune,Mumbai,22:40,06:15\n+ 1 day,1 Stop,7h 35m,Free Meal,"11,063"
8,Vistara,Pune,Mumbai,23:10,22:55\n+ 1 day,1 Stop,23h 45m,Free Meal,"11,928"
9,Vistara,Pune,Mumbai,19:10,07:55\n+ 1 day,1 Stop,12h 45m,Free Meal,"12,132"
10,Vistara,Pune,Mumbai,23:10,08:10\n+ 1 day,1 Stop,9h 00m,Free Meal,"12,348"
11,Air India,Pune,Mumbai,21:05,07:00\n+ 1 day,1 Stop,9h 55m,Free Meal,"12,873"
12,Air India,Pune,Mumbai,19:00,07:00\n+ 1 day,1 Stop,12h 00m,Free Meal,"12,873"
13,Air India,Pune,Mumbai,18:00,07:00\n+ 1 day,1 Stop,13h 00m,Free Meal,"12,873"
14,Air India,Pune,Mumbai,16:35,07:00\n+ 1 day,1 Stop,14h 25m,Free Meal,"12,873"
15,Air India,Pune,Mumbai,15:30,07:00\n+ 1 day,1 Stop,15h 30m,Free Meal,"12,873"
16,Air India,Pune,Mumbai,21:05,15:20\n+ 1 day,1 Stop,18h 15m,Free Meal,"12,873"
17,Air India,Pune,Mumbai,19:00,15:20\n+ 1 day,1 Stop,20h 20m,Free Meal,"12,873"
18,Air India,Pune,Mumbai,21:05,18:10\n+ 1 day,1 Stop,21h 05m,Free Meal,"12,873"
19,Air India,Pune,Mumbai,18:00,15:20\n+ 1 day,1 Stop,21h 20m,Free Meal,"12,873"
20,Air India,Pune,Mumbai,16:35,15:20\n+ 1 day,1 Stop,22h 45m,Free Meal,"12,873"
21,Air India,Pune,Mumbai,19:00,18:10\n+ 1 day,1 Stop,23h 10m,Free Meal,"12,873"
22,Air India,Pune,Mumbai,15:30,15:20\n+ 1 day,1 Stop,23h 50m,Free Meal,"12,873"
23,Vistara,Pune,Mumbai,21:55,08:10\n+ 1 day,1 Stop,10h 15m,Free Meal,"13,293"
24,Vistara,Pune,Mumbai,18:30,08:10\n+ 1 day,1 Stop,13h 40m,Free Meal,"13,293"
25,Vistara,Pune,Mumbai,17:35,08:10\n+ 1 day,1 Stop,14h 35m,Free Meal,"13,293"
26,Vistara,Pune,Mumbai,15:45,08:10\n+ 1 day,1 Stop,16h 25m,Free Meal,"13,293"
27,Vistara,Pune,Mumbai,14:40,08:10\n+ 1 day,1 Stop,17h 30m,Free Meal,"13,293"
28,Vistara,Pune,Mumbai,17:55,22:05,1 Stop,4h 10m,Free Meal,"14,165"
29,Vistara,Pune,Mumbai,17:30,22:05,1 Stop,4h 35m,Free Meal,"14,165"
30,Vistara,Pune,Mumbai,17:35,22:55,1 Stop,5h 20m,Free Meal,"14,236"
31,Vistara,Pune,Mumbai,18:30,00:35\n+ 1 day,1 Stop,6h 05m,Free Meal,"14,236"
32,Vistara,Pune,Mumbai,17:35,00:35\n+ 1 day,1 Stop,7h 00m,Free Meal,"14,236"
33,Vistara,Pune,Mumbai,15:45,22:55,1 Stop,7h 10m,Free Meal,"14,236"
34,Vistara,Pune,Mumbai,14:40,22:55,1 Stop,8h 15m,Free Meal,"14,236"
35,Vistara,Pune,Mumbai,15:45,00:35\n+ 1 day,1 Stop,8h 50m,Free Meal,"14,236"
36,Go First,Pune,Mumbai,23:45,11:45\n+ 1 day,1 Stop,12h 00m,Free Meal,"14,793"
37,Go First,Pune,Mumbai,21:15,11:45\n+ 1 day,1 Stop,14h 30m,NaN,"14,793"
38,Air India,Pune,Mumbai,21:00,07:00\n+ 1 day,2 Stop(s),10h 00m,NaN,"17,178"
39,Air India,Pune,Mumbai,21:00,15:20\n+ 1 day,2 Stop(s),18h 20m,NaN,"17,178"
40,Vistara,Pune,Mumbai,21:30,22:05\n+ 1 day,1 Stop,24h 35m,NaN,"17,630"
41,Air India,Pune,Mumbai,13:30,07:00\n+ 1 day,2 Stop(s),17h 30m,NaN,"18,543"
42,Vistara,Pune,Mumbai,19:10,22:05\n+ 1 day,1 Stop,26h 55m,NaN,"19,205"
43,Vistara,Pune,Mumbai,13:20,22:55\n+ 1 day,2 Stop(s),33h 35m,NaN,"35,600"

In [192]:
Flight=pd.concat([Flight,flights4,flights5,flights6,flights7,flights8],ignore_index=True)

In [193]:
Flight

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,Go First,Chennai,New Delhi,22:30,07:35\n+ 1 day,1 Stop,9h 05m,Free Meal,"6,417"
1,Go First,Chennai,New Delhi,21:00,07:35\n+ 1 day,1 Stop,10h 35m,Free Meal,"6,417"
2,Go First,Chennai,New Delhi,20:00,07:35\n+ 1 day,1 Stop,11h 35m,Free Meal,"6,417"
3,Go First,Chennai,New Delhi,18:00,07:35\n+ 1 day,1 Stop,13h 35m,Free Meal,"6,417"
4,SpiceJet,Chennai,New Delhi,18:50,21:30,Non Stop,2h 40m,Free Meal,"6,610"
...,...,...,...,...,...,...,...,...,...
722,Air India,Pune,Mumbai,21:00,15:20\n+ 1 day,2 Stop(s),18h 20m,NaN,"17,178"
723,Vistara,Pune,Mumbai,21:30,22:05\n+ 1 day,1 Stop,24h 35m,NaN,"17,630"
724,Air India,Pune,Mumbai,13:30,07:00\n+ 1 day,2 Stop(s),17h 30m,NaN,"18,543"
725,Vistara,Pune,Mumbai,19:10,22:05\n+ 1 day,1 Stop,26h 55m,NaN,"19,205"
726,Vistara,Pune,Mumbai,13:20,22:55\n+ 1 day,2 Stop(s),33h 35m,NaN,"35,600"

In [195]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=HYD&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1012298535281'
driver.get(url)

In [196]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights9 = pd.DataFrame({})
flights9['Airline'] = Airline
flights9['Destination'] = list1
flights9['Source'] = list2
flights9['Arrival_time'] = Arr_t
flights9['Departure_time'] =Dep_t
flights9['Total_Stops']=Total_s
flights9['Total_Duration']=duration
flights9['Additional_Info']=pd.Series(Add_info)
flights9['Price']=price
flights9

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,Alliance Air,Hyderabad,Bangalore,19:40,21:15,Non Stop,1h 35m,No Meal Fare,"4,429"
1,Air Asia,Hyderabad,Bangalore,12:55,14:05,Non Stop,1h 10m,Free Meal,"4,846"
2,Air Asia,Hyderabad,Bangalore,15:40,16:50,Non Stop,1h 10m,Free Meal,"4,846"
3,Air Asia,Hyderabad,Bangalore,16:10,17:20,Non Stop,1h 10m,Free Meal,"4,846"
4,Vistara,Hyderabad,Bangalore,18:30,19:55,Non Stop,1h 25m,Free Meal,"4,847"
...,...,...,...,...,...,...,...,...,...
69,Vistara,Hyderabad,Bangalore,19:40,19:50\n+ 1 day,1 Stop,24h 10m,NaN,"17,838"
70,Vistara,Hyderabad,Bangalore,18:45,19:50\n+ 1 day,1 Stop,25h 05m,NaN,"17,838"
71,Air India,Hyderabad,Bangalore,21:20,12:25\n+ 1 day,1 Stop,15h 05m,NaN,"20,106"
72,Air India,Hyderabad,Bangalore,19:15,12:25\n+ 1 day,1 Stop,17h 10m,NaN,"20,106"
73,Vistara,Hyderabad,Bangalore,21:35,12:15\n+ 1 day,1 Stop,14h 40m,NaN,"27,876"

In [206]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=LKO&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1605470482032'
driver.get(url)

In [207]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights0 = pd.DataFrame({})
flights0['Airline'] = Airline
flights0['Destination'] = list1
flights0['Source'] = list2
flights0['Arrival_time'] = Arr_t
flights0['Departure_time'] =Dep_t
flights0['Total_Stops']=Total_s
flights0['Total_Duration']=duration
flights0['Additional_Info']=pd.Series(Add_info)
flights0['Price']=price
flights0

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,IndiGo,Lucknow,Bangalore,19:35,22:10,Non Stop,2h 35m,Free Meal,"3,382"
1,Air Asia,Lucknow,Bangalore,18:45,21:10,Non Stop,2h 25m,Free Meal,"3,433"
2,IndiGo,Lucknow,Bangalore,18:00,00:40\n+ 1 day,1 Stop,6h 40m,Free Meal,"6,408"
3,IndiGo,Lucknow,Bangalore,16:20,00:40\n+ 1 day,1 Stop,8h 20m,Free Meal,"6,408"
4,Air Asia,Lucknow,Bangalore,17:55,22:55,1 Stop,5h 00m,Free Meal,"6,422"
...,...,...,...,...,...,...,...,...,...
71,Vistara,Lucknow,Bangalore,21:35,14:50\n+ 1 day,2 Stop(s),17h 15m,NaN,"18,107"
72,Vistara,Lucknow,Bangalore,20:30,14:50\n+ 1 day,2 Stop(s),18h 20m,NaN,"21,681"
73,Vistara,Lucknow,Bangalore,18:30,14:50\n+ 1 day,2 Stop(s),20h 20m,NaN,"22,833"
74,Vistara,Lucknow,Bangalore,21:35,14:50\n+ 1 day,2 Stop(s),17h 15m,NaN,"23,046"
75,Vistara,Lucknow,Bangalore,21:35,14:50\n+ 1 day,2 Stop(s),17h 15m,NaN,"26,721"

In [199]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=HYD&originCountry=IN&destination=DEL&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=818947666808'
driver.get(url)

In [200]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights01 = pd.DataFrame({})
flights01['Airline'] = Airline
flights01['Destination'] = list1
flights01['Source'] = list2
flights01['Arrival_time'] = Arr_t
flights01['Departure_time'] =Dep_t
flights01['Total_Stops']=Total_s
flights01['Total_Duration']=duration
flights01['Additional_Info']=pd.Series(Add_info)
flights01['Price']=price
flights01

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,IndiGo,New Delhi,Hyderabad,22:45,01:10\n+ 1 day,Non Stop,2h 25m,Free Meal,"7,732"
1,Air Asia,New Delhi,Hyderabad,14:40,23:05,1 Stop,8h 25m,Free Meal,"7,732"
2,Air Asia,New Delhi,Hyderabad,14:20,01:25\n+ 1 day,1 Stop,11h 05m,Free Meal,"7,732"
3,Air India,New Delhi,Hyderabad,20:30,23:10,Non Stop,2h 40m,Free Meal,"7,733"
4,IndiGo,New Delhi,Hyderabad,18:10,20:40,Non Stop,2h 30m,Free Meal,"8,257"
5,Air Asia,New Delhi,Hyderabad,14:20,22:50,1 Stop,8h 30m,Free Meal,"8,259"
6,Vistara,New Delhi,Hyderabad,17:40,19:55,Non Stop,2h 15m,Free Meal,"8,468"
7,IndiGo,New Delhi,Hyderabad,20:15,22:40,Non Stop,2h 25m,Free Meal,"8,782"
8,IndiGo,New Delhi,Hyderabad,20:05,06:40\n+ 1 day,1 Stop,10h 35m,Free Meal,"9,990"
9,IndiGo,New Delhi,Hyderabad,22:20,07:50\n+ 1 day,1 Stop,9h 30m,Free Meal,"10,232"
10,IndiGo,New Delhi,Hyderabad,22:20,08:40\n+ 1 day,1 Stop,10h 20m,Free Meal,"10,232"
11,IndiGo,New Delhi,Hyderabad,14:10,16:30,Non Stop,2h 20m,Free Meal,"10,357"
12,IndiGo,New Delhi,Hyderabad,11:50,14:15,Non Stop,2h 25m,Free Meal,"10,357"
13,SpiceJet,New Delhi,Hyderabad,19:35,21:50,Non Stop,2h 15m,Free Meal,"10,726"
14,IndiGo,New Delhi,Hyderabad,12:15,20:10,1 Stop,7h 55m,Free Meal,"10,777"
15,IndiGo,New Delhi,Hyderabad,16:30,18:55,Non Stop,2h 25m,Free Meal,"11,092"
16,IndiGo,New Delhi,Hyderabad,21:35,00:05\n+ 1 day,Non Stop,2h 30m,Free Meal,"11,092"
17,Air Asia,New Delhi,Hyderabad,14:20,20:45,1 Stop,6h 25m,Free Meal,"11,265"
18,Air Asia,New Delhi,Hyderabad,21:45,08:35\n+ 1 day,1 Stop,10h 50m,Free Meal,"11,619"
19,Air Asia,New Delhi,Hyderabad,19:40,01:25\n+ 1 day,1 Stop,5h 45m,Free Meal,"12,772"
20,IndiGo,New Delhi,Hyderabad,14:50,19:35,1 Stop,4h 45m,Free Meal,"12,953"
21,Air Asia,New Delhi,Hyderabad,17:25,01:45\n+ 1 day,1 Stop,8h 20m,Free Meal,"13,844"
22,IndiGo,New Delhi,Hyderabad,14:25,00:25\n+ 1 day,1 Stop,10h 00m,Free Meal,"15,417"
23,Air Asia,New Delhi,Hyderabad,17:55,01:45\n+ 1 day,1 Stop,7h 50m,Free Meal,"15,528"
24,IndiGo,New Delhi,Hyderabad,14:25,20:15,1 Stop,5h 50m,Free Meal,"16,782"
25,Vistara,New Delhi,Hyderabad,20:40,10:35\n+ 1 day,1 Stop,13h 55m,Free Meal,"19,357"
26,Vistara,New Delhi,Hyderabad,20:30,22:45,Non Stop,2h 15m,Free Meal,"19,451"
27,Vistara,New Delhi,Hyderabad,13:15,16:00,Non Stop,2h 45m,Free Meal,"19,451"
28,IndiGo,New Delhi,Hyderabad,19:30,00:25\n+ 1 day,1 Stop,4h 55m,Free Meal,"21,167"
29,Vistara,New Delhi,Hyderabad,20:40,21:25\n+ 1 day,1 Stop,24h 45m,Free Meal,"21,247"
30,Vistara,New Delhi,Hyderabad,20:40,22:20\n+ 1 day,1 Stop,25h 40m,Free Meal,"21,247"
31,Vistara,New Delhi,Hyderabad,20:40,23:45\n+ 1 day,1 Stop,27h 05m,Free Meal,"21,247"
32,Vistara,New Delhi,Hyderabad,20:40,14:10\n+ 1 day,1 Stop,17h 30m,Free Meal,"23,347"
33,Vistara,New Delhi,Hyderabad,20:40,20:30\n+ 1 day,1 Stop,23h 50m,NaN,"23,347"
34,Vistara,New Delhi,Hyderabad,12:55,01:00\n+ 1 day,1 Stop,12h 05m,NaN,"24,428"
35,Vistara,New Delhi,Hyderabad,12:55,18:05,1 Stop,5h 10m,NaN,"25,373"
36,Vistara,New Delhi,Hyderabad,12:55,19:45,1 Stop,6h 50m,NaN,"25,373"
37,Vistara,New Delhi,Hyderabad,12:55,20:40,1 Stop,7h 45m,NaN,"25,373"
38,Vistara,New Delhi,Hyderabad,12:55,00:10\n+ 1 day,1 Stop,11h 15m,NaN,"25,373"
39,Vistara,New Delhi,Hyderabad,12:55,07:55\n+ 1 day,1 Stop,19h 00m,NaN,"25,373"
40,Vistara,New Delhi,Hyderabad,12:55,08:35\n+ 1 day,1 Stop,19h 40m,NaN,"25,373"
41,Vistara,New Delhi,Hyderabad,12:55,12:40\n+ 1 day,1 Stop,23h 45m,NaN,"25,373"
42,Vistara,New Delhi,Hyderabad,12:55,14:05\n+ 1 day,1 Stop,25h 10m,NaN,"25,373"
43,Vistara,New Delhi,Hyderabad,12:55,14:50\n+ 1 day,1 Stop,25h 55m,NaN,"25,373"
44,Vistara,New Delhi,Hyderabad,20:40,12:40\n+ 1 day,1 Stop,16h 00m,NaN,"25,972"
45,Vistara,New Delhi,Hyderabad,12:55,10:20\n+ 1 day,2 Stop(s),21h 25m,NaN,"27,788"
46,Vistara,New Delhi,Hyderabad,12:55,17:10\n+ 1 day,2 Stop(s),28h 15m,NaN,"27,788"
47,Vistara,New Delhi,Hyderabad,12:55,23:00,1 Stop,10h 05m,NaN,"28,208"
48,Vistara,New Delhi,Hyderabad,12:55,22:00,2 Stop(s),9h 05m,NaN,"28,345"
49,Vistara,New Delhi,Hyderabad,12:55,07:55\n+ 1 day,2 Stop(s),19h 00m,NaN,"29,920"
50,Vistara,New Delhi,Hyderabad,12:55,22:00\n+ 1 day,2 Stop(s),33h 05m,NaN,"30,518"
51,Vistara,New Delhi,Hyderabad,12:55,10:20\n+ 1 day,2 Stop(s),21h 25m,NaN,"31,148"
52,Vistara,New Delhi,Hyderabad,12:55,17:10\n+ 1 day,2 Stop(s),28h 15m,NaN,"31,148"
53,Vistara,New Delhi,Hyderabad,20:40,09:40\n+ 1 day,1 Stop,13h 00m,NaN,"31,358"
54,Vistara,New Delhi,Hyderabad,12:55,11:00\n+ 1 day,1 Stop,22h 05m,NaN,"31,883"
55,Vistara,New Delhi,Hyderabad,12:55,07:55\n+ 1 day,2 Stop(s),19h 00m,NaN,"33,668"
56,Vistara,New Delhi,Hyderabad,12:55,21:55,1 Stop,9h 00m,NaN,"45,397"

In [203]:
# Connecting to the webdriver.
driver = webdriver.Chrome(r'C:\Users\sunee\Downloads\chromedriver_win32 (2)\chromedriver.exe')

# Getting the desired url.
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=CCU&destinationCountry=IN&flight_depart_date=10%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=952359646259'
driver.get(url)

In [204]:
airline=driver.find_elements("xpath",'//span[@class="i-b text ellipsis"]')
len(airline)
Airline=[]
for i in airline:
    Airline.append(i.text)
Airline

flight_no=driver.find_elements("xpath",'//p[@class="normal fs-11 font-lightestgrey no-wrap fl-no"]')
len(flight_no)

Flight_no=[]
for i in flight_no:
    Flight_no.append(i.text)
Flight_no

source=driver.find_elements('xpath','//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
len(source)

sources=[]
for i in source:
    sources.append(i.text)
sources

list1 = [sources[i] for i in range(len(sources)) if i % 2 != 0]
len(list1)
list1

list2=sources[::2]

len(list2)
list2

duration_tag=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(duration_tag)

duration=[]
for i in duration_tag:
    duration.append(i.text)
duration

arr_t=driver.find_elements("xpath",'//div[@class="fs-15 bold time"]')
len(arr_t)

Arr_t=[]
for i in arr_t:
    Arr_t.append(i.text)
Arr_t

dep_t=driver.find_elements("xpath",'//p[@class="bold fs-15 mb-2 pr time"]')
len(dep_t)

Dep_t=[]
for i in dep_t:
    Dep_t.append(i.text)
Dep_t    

total_t=driver.find_elements("xpath",'//p[@class="fs-12 bold du mb-2"]')
len(total_t)

Total_t=[]
for i in total_t:
    Total_t.append(i.text)
Total_t    

total_s=driver.find_elements("xpath",'//div[@class=" font-lightgrey fs-10 tipsy i-b fs-10"]')
len(total_s)

Total_s=[]
for i in total_s:
    Total_s.append(i.text)
Total_s    

cost=driver.find_elements("xpath",'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
len(cost)

price=[]
for i in cost:
    price.append(i.text)
price    

meal_tag=driver.find_elements("xpath",'//span[@class="text"]')
len(meal_tag)

Add_info=[]
for i in meal_tag:
    Add_info.append(i.text)
Add_info    


# Creating the Dataframe.

flights02 = pd.DataFrame({})
flights02['Airline'] = Airline
flights02['Destination'] = list1
flights02['Source'] = list2
flights02['Arrival_time'] = Arr_t
flights02['Departure_time'] =Dep_t
flights02['Total_Stops']=Total_s
flights02['Total_Duration']=duration
flights02['Additional_Info']=pd.Series(Add_info)
flights02['Price']=price
flights02

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,IndiGo,Kolkata,Bangalore,17:25,22:25,1 Stop,5h 00m,Free Meal,"7,579"
1,Air Asia,Kolkata,Bangalore,20:55,02:30\n+ 1 day,1 Stop,5h 35m,Free Meal,"7,579"
2,IndiGo,Kolkata,Bangalore,14:40,20:30,1 Stop,5h 50m,Free Meal,"7,579"
3,IndiGo,Kolkata,Bangalore,13:55,20:20,1 Stop,6h 25m,Free Meal,"7,579"
4,IndiGo,Kolkata,Bangalore,21:55,05:50\n+ 1 day,1 Stop,7h 55m,Free Meal,"7,579"
...,...,...,...,...,...,...,...,...,...
80,Vistara,Kolkata,Bangalore,21:35,16:50\n+ 1 day,1 Stop,19h 15m,NaN,"20,526"
81,IndiGo,Kolkata,Bangalore,11:50,20:45,1 Stop,8h 55m,NaN,"21,007"
82,Vistara,Kolkata,Bangalore,21:35,09:40\n+ 1 day,1 Stop,12h 05m,NaN,"22,311"
83,Vistara,Kolkata,Bangalore,20:30,18:05\n+ 1 day,2 Stop(s),21h 35m,NaN,"29,314"
84,Vistara,Kolkata,Bangalore,20:30,22:20\n+ 1 day,2 Stop(s),25h 50m,NaN,"29,314"

In [208]:
Flight=pd.concat([Flight,flights9,flights0,flights01,flights02],ignore_index=True)

In [209]:
Flight

,Airline,Destination,Source,Arrival_time,Departure_time,Total_Stops,Total_Duration,Additional_Info,Price
0,Go First,Chennai,New Delhi,22:30,07:35\n+ 1 day,1 Stop,9h 05m,Free Meal,"6,417"
1,Go First,Chennai,New Delhi,21:00,07:35\n+ 1 day,1 Stop,10h 35m,Free Meal,"6,417"
2,Go First,Chennai,New Delhi,20:00,07:35\n+ 1 day,1 Stop,11h 35m,Free Meal,"6,417"
3,Go First,Chennai,New Delhi,18:00,07:35\n+ 1 day,1 Stop,13h 35m,Free Meal,"6,417"
4,SpiceJet,Chennai,New Delhi,18:50,21:30,Non Stop,2h 40m,Free Meal,"6,610"
...,...,...,...,...,...,...,...,...,...
1016,Vistara,Kolkata,Bangalore,21:35,16:50\n+ 1 day,1 Stop,19h 15m,NaN,"20,526"
1017,IndiGo,Kolkata,Bangalore,11:50,20:45,1 Stop,8h 55m,NaN,"21,007"
1018,Vistara,Kolkata,Bangalore,21:35,09:40\n+ 1 day,1 Stop,12h 05m,NaN,"22,311"
1019,Vistara,Kolkata,Bangalore,20:30,18:05\n+ 1 day,2 Stop(s),21h 35m,NaN,"29,314"
1020,Vistara,Kolkata,Bangalore,20:30,22:20\n+ 1 day,2 Stop(s),25h 50m,NaN,"29,314"

In [211]:
Flight.to_csv('Flight_data.csv')

In [212]:
Flight.to_excel('Flights_data.xlsx')